import { describe, expect, it } from "vitest";
import {
  buildEventReportHtml,
  type EventReportExport,
  escapeHtml,
} from "../../src/pages/event-report/exporters/html";

const LABELS = {
  fieldOrganizer: "Organizer (Tenant)",
  fieldEventId: "Event ID",
  fieldSchedule: "Schedule (UTC)",
  fieldStatus: "Status",
  fieldGeneratedAt: "Generated at",
  coverNoteLabel: "Cover note",
  sectionSummary: "Summary",
  sectionScoreboard: "Final scoreboard",
  sectionProblems: "Per-problem breakdown",
  sectionDisruptions: "Disruption / Red Team log",
  sectionFooter: "Footer",
  statTeams: "Teams",
  statParticipants: "Participants",
  statProblems: "Problems",
  statTotalDeployments: "Total deployments",
  statSuccessRate: "Deploy success rate",
  statSuccessRateBreakdown: "1 ok / 1 failed",
  successRateFormatted: "50.0%",
  colRank: "Rank",
  colTeam: "Team",
  colScore: "Score",
  colProblemsSolved: "Problems solved",
  colProblemId: "Problem ID",
  colRegion: "Region",
  colSolvedCount: "Teams solved",
  colAvgScore: "Avg score",
  colDeployments: "Deploys (ok / total)",
  colOccurredAt: "Occurred at",
  colSource: "Source",
  colPoints: "Points",
  scoreboardEmpty: "No score events.",
  problemsEmpty: "No problems.",
  disruptionsDescription: "Timeline of wrong flag submissions.",
  footerGeneratedBy: "Generated by TenkaCloud Application Admin Console",
  footerBranding: "TenkaCloud — Multi-tenant cloud competition platform on AWS",
} as const;

function makeExport(overrides: Partial<EventReportExport> = {}): EventReportExport {
  return {
    locale: "en",
    title: "Event Report",
    eventName: "Spring Cloud Cup 2026",
    eventId: "01HXEVENT0000000000000ABCD",
    tenantName: "ACME Cloud Academy",
    scheduleRange: "2026-05-21 09:00 UTC — 2026-05-21 12:00 UTC",
    status: "ENDED",
    generatedAt: "2026-05-21 13:00",
    coverNote: "Custom intro for ACME — closing remarks.",
    summary: {
      teamCount: 2,
      participantCount: 2,
      problemCount: 1,
      totalDeployments: 2,
      successfulDeployments: 1,
      failedDeployments: 1,
      successRate: 0.5,
    },
    scoreboard: [
      { rank: 1, teamId: "team-A", teamName: "Team Alpha", totalScore: 100, problemsSolved: 1 },
      { rank: 2, teamId: "team-B", teamName: "Team Bravo", totalScore: -10, problemsSolved: 0 },
    ],
    breakdown: [
      {
        problemId: "battle/redis-spike",
        defaultRegion: "ap-northeast-1",
        solvedCount: 1,
        avgScore: 45,
        deploymentsCount: 2,
        successfulCount: 1,
      },
    ],
    disruptions: [
      {
        occurredAt: "2026-05-21T10:35:00Z",
        problemId: "battle/redis-spike",
        teamId: "team-B",
        teamName: "Team Bravo",
        source: "flag-wrong",
        points: -10,
      },
    ],
    labels: LABELS,
    ...overrides,
  };
}

describe("buildEventReportHtml", () => {
  it("should emit a self-contained <!doctype html> document with inline <style>", () => {
    const html = buildEventReportHtml(makeExport());
    expect(html.startsWith("<!doctype html>")).toBe(true);
    expect(html).toContain("<html lang=");
    expect(html).toContain('<meta charset="utf-8">');
    expect(html).toContain("<style>");
    expect(html).toContain("</style>");
    // 外部 asset (link rel=stylesheet / <img src=…/>) を一切含まない (= self-contained 要件)
    expect(html).not.toMatch(/<link\s/i);
    expect(html).not.toMatch(/<img\s/i);
    expect(html).not.toMatch(/<script\s/i);
  });

  it("should include the event-report-page container class on the main element", () => {
    const html = buildEventReportHtml(makeExport());
    expect(html).toMatch(/<main\s+class="event-report-page">/);
  });

  it("should include all 6 sections when disruptions are present", () => {
    const html = buildEventReportHtml(makeExport());
    // Header (h1 = title)
    expect(html).toContain(">Event Report<");
    // Cover note paragraph
    expect(html).toContain("Custom intro for ACME");
    // Summary heading
    expect(html).toContain(">Summary<");
    // Scoreboard
    expect(html).toContain(">Final scoreboard<");
    expect(html).toContain("Team Alpha");
    // Problem breakdown
    expect(html).toContain(">Per-problem breakdown<");
    expect(html).toContain("battle/redis-spike");
    // Disruption section
    expect(html).toContain(">Disruption / Red Team log<");
    // Footer
    expect(html).toContain("Generated by TenkaCloud Application Admin Console");
  });

  it("should omit the disruption section when there are no negative-point events", () => {
    const html = buildEventReportHtml(makeExport({ disruptions: [] }));
    expect(html).not.toContain("Disruption / Red Team log");
  });

  it("should render GFM-equivalent tables with <thead>/<tbody> for scoreboard / breakdown / disruptions", () => {
    const html = buildEventReportHtml(makeExport());
    const tableHeads = html.match(/<thead>/g) ?? [];
    // scoreboard + breakdown + disruptions = 3 tables with thead
    expect(tableHeads.length).toBeGreaterThanOrEqual(3);
    expect(html).toMatch(
      /<table>[\s\S]*<thead>[\s\S]*<\/thead>[\s\S]*<tbody>[\s\S]*<\/tbody>[\s\S]*<\/table>/,
    );
  });

  it("should HTML-escape user-supplied cover notes to prevent XSS", () => {
    const html = buildEventReportHtml(makeExport({ coverNote: '<script>alert("x")</script>' }));
    expect(html).not.toContain("<script>alert");
    expect(html).toContain("&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;");
  });

  it("should HTML-escape team and problem names so an attacker-controlled team name cannot inject markup", () => {
    const html = buildEventReportHtml(
      makeExport({
        scoreboard: [
          { rank: 1, teamId: "x", teamName: "<img src=x>", totalScore: 0, problemsSolved: 0 },
        ],
      }),
    );
    expect(html).not.toMatch(/<img\s+src=x>/i);
    expect(html).toContain("&lt;img src=x&gt;");
  });

  it("should switch the html lang attribute based on locale", () => {
    expect(buildEventReportHtml(makeExport({ locale: "ja" }))).toMatch(/<html lang="ja">/);
    expect(buildEventReportHtml(makeExport({ locale: "en" }))).toMatch(/<html lang="en">/);
  });

  it("should declare an A4 @page rule for browser print-to-PDF", () => {
    expect(buildEventReportHtml(makeExport())).toMatch(/@page\s*\{[^}]*size:\s*A4/);
  });

  it("should use a serif font stack for print-readability parity with the page", () => {
    expect(buildEventReportHtml(makeExport())).toMatch(/font-family:[^;]*serif/i);
  });

  it("should render the empty-state paragraph instead of a table when the scoreboard is empty", () => {
    const html = buildEventReportHtml(makeExport({ scoreboard: [] }));
    expect(html).toContain("No score events.");
    // 空のときは scoreboard 行 (= "N pt" セル) を出さない。
    expect(html).not.toContain(" pt</td>");
  });

  it("should render the empty-state paragraph instead of a table when the breakdown is empty", () => {
    const html = buildEventReportHtml(makeExport({ breakdown: [] }));
    expect(html).toContain("No problems.");
  });
});

describe("escapeHtml", () => {
  it("should escape the 5 entities (&, <, >, \", ')", () => {
    expect(escapeHtml("a & b < c > d \" e ' f")).toBe("a &amp; b &lt; c &gt; d &quot; e &#39; f");
  });
});
