import { describe, expect, it } from "vitest";
import type { EventReportExport } from "../../src/pages/event-report/exporters/html";
import {
  buildEventReportMarkdown,
  escapeMarkdownCell,
} from "../../src/pages/event-report/exporters/markdown";

const LABELS = {
  fieldOrganizer: "Organizer (Tenant)",
  fieldEventId: "Event ID",
  fieldSchedule: "Schedule (UTC)",
  fieldStatus: "Status",
  fieldGeneratedAt: "Generated at",
  coverNoteLabel: "Cover note",
  sectionSummary: "Summary",
  sectionScoreboard: "Final scoreboard",
  sectionProblems: "Per-problem breakdown",
  sectionDisruptions: "Disruption / Red Team log",
  sectionFooter: "Footer",
  statTeams: "Teams",
  statParticipants: "Participants",
  statProblems: "Problems",
  statTotalDeployments: "Total deployments",
  statSuccessRate: "Deploy success rate",
  statSuccessRateBreakdown: "1 ok / 1 failed",
  successRateFormatted: "50.0%",
  colRank: "Rank",
  colTeam: "Team",
  colScore: "Score",
  colProblemsSolved: "Problems solved",
  colProblemId: "Problem ID",
  colRegion: "Region",
  colSolvedCount: "Teams solved",
  colAvgScore: "Avg score",
  colDeployments: "Deploys (ok / total)",
  colOccurredAt: "Occurred at",
  colSource: "Source",
  colPoints: "Points",
  scoreboardEmpty: "No score events.",
  problemsEmpty: "No problems.",
  disruptionsDescription: "Timeline of wrong flag submissions.",
  footerGeneratedBy: "Generated by TenkaCloud Application Admin Console",
  footerBranding: "TenkaCloud — Multi-tenant cloud competition platform on AWS",
} as const;

function makeExport(overrides: Partial<EventReportExport> = {}): EventReportExport {
  return {
    locale: "en",
    title: "Event Report",
    eventName: "Spring Cloud Cup 2026",
    eventId: "01HXEVENT0000000000000ABCD",
    tenantName: "ACME Cloud Academy",
    scheduleRange: "2026-05-21 09:00 UTC — 2026-05-21 12:00 UTC",
    status: "ENDED",
    generatedAt: "2026-05-21 13:00",
    coverNote: "Closing remarks for ACME.",
    summary: {
      teamCount: 2,
      participantCount: 2,
      problemCount: 1,
      totalDeployments: 2,
      successfulDeployments: 1,
      failedDeployments: 1,
      successRate: 0.5,
    },
    scoreboard: [
      { rank: 1, teamId: "team-A", teamName: "Team Alpha", totalScore: 100, problemsSolved: 1 },
      { rank: 2, teamId: "team-B", teamName: "Team Bravo", totalScore: -10, problemsSolved: 0 },
    ],
    breakdown: [
      {
        problemId: "battle/redis-spike",
        defaultRegion: "ap-northeast-1",
        solvedCount: 1,
        avgScore: 45,
        deploymentsCount: 2,
        successfulCount: 1,
      },
    ],
    disruptions: [
      {
        occurredAt: "2026-05-21T10:35:00Z",
        problemId: "battle/redis-spike",
        teamId: "team-B",
        teamName: "Team Bravo",
        source: "flag-wrong",
        points: -10,
      },
    ],
    labels: LABELS,
    ...overrides,
  };
}

describe("buildEventReportMarkdown", () => {
  it("should start with a level-1 heading for the report title", () => {
    expect(buildEventReportMarkdown(makeExport()).startsWith("# Event Report\n")).toBe(true);
  });

  it("should put each major section as a level-2 heading", () => {
    const md = buildEventReportMarkdown(makeExport());
    expect(md).toContain("## Summary");
    expect(md).toContain("## Final scoreboard");
    expect(md).toContain("## Per-problem breakdown");
    expect(md).toContain("## Disruption / Red Team log");
    expect(md).toContain("## Footer");
  });

  it("should embed the cover note as a paragraph between the meta block and the Summary section", () => {
    const md = buildEventReportMarkdown(makeExport({ coverNote: "Closing remarks for ACME." }));
    const coverIdx = md.indexOf("Closing remarks for ACME.");
    const summaryIdx = md.indexOf("## Summary");
    expect(coverIdx).toBeGreaterThan(0);
    expect(coverIdx).toBeLessThan(summaryIdx);
  });

  it("should render the scoreboard as a GFM table with a separator row", () => {
    const md = buildEventReportMarkdown(makeExport());
    expect(md).toContain("| Rank | Team | Score | Problems solved |");
    expect(md).toContain("| --- | --- | --- | --- |");
    expect(md).toContain("| 1 | Team Alpha | 100 pt | 1 |");
  });

  it("should render the per-problem breakdown as a GFM table with backticked problem IDs", () => {
    const md = buildEventReportMarkdown(makeExport());
    expect(md).toContain("| `battle/redis-spike` | ap-northeast-1 | 1 | 45 | 1 / 2 |");
  });

  it("should omit the disruption section when there are no negative-point events", () => {
    const md = buildEventReportMarkdown(makeExport({ disruptions: [] }));
    expect(md).not.toContain("## Disruption / Red Team log");
  });

  it("should end the document with exactly one trailing newline (POSIX-friendly)", () => {
    const md = buildEventReportMarkdown(makeExport());
    expect(md.endsWith("\n")).toBe(true);
    expect(md.endsWith("\n\n")).toBe(false);
  });

  it("should backtick the eventId in the meta list", () => {
    const md = buildEventReportMarkdown(makeExport());
    expect(md).toContain("- **Event ID**: `01HXEVENT0000000000000ABCD`");
  });

  it("should escape `|` inside team names so it does not break the GFM table", () => {
    const md = buildEventReportMarkdown(
      makeExport({
        scoreboard: [{ rank: 1, teamId: "x", teamName: "A | B", totalScore: 0, problemsSolved: 0 }],
      }),
    );
    expect(md).toContain("| 1 | A \\| B | 0 pt | 0 |");
  });

  it("should render the empty-state label instead of a table when the scoreboard is empty", () => {
    const md = buildEventReportMarkdown(makeExport({ scoreboard: [] }));
    expect(md).toContain("## Final scoreboard");
    expect(md).toContain("No score events.");
    // 空のときは GFM table の separator 行を出さない。
    expect(md).not.toContain("| Rank | Team | Score | Problems solved |");
  });

  it("should render the empty-state label instead of a table when the breakdown is empty", () => {
    const md = buildEventReportMarkdown(makeExport({ breakdown: [] }));
    expect(md).toContain("## Per-problem breakdown");
    expect(md).toContain("No problems.");
  });
});

describe("escapeMarkdownCell", () => {
  it("should escape backslashes, pipes, and collapse newlines into spaces", () => {
    expect(escapeMarkdownCell("a | b\nc\\d")).toBe("a \\| b c\\\\d");
  });
});
