import sonarjs from "eslint-plugin-sonarjs";
import tseslint from "typescript-eslint";

// Keep the initial typed-lint scope bounded to repository automation scripts so rollout stays measurable.
const typedSourceFiles = ["scripts/**/*.ts"];
const testFiles = ["**/*.test.ts", "**/*.spec.ts"];

export default [
  {
    // This list must stay a superset of the generated / vendored paths `.gitignore` excludes.
    // When it drifted, `eslint .` walked into build output and nested agent worktrees and
    // reported 186,110 errors across 15,640 files instead of the 1,694 the repository actually
    // owns — and the file set differed per machine, so the suppressions ceiling below could not
    // have been reproduced in CI. `lint-eslint-scope` (scripts/lint/check-eslint-ignore-parity.ts)
    // now fails the gate when a git-ignored directory holding lintable files is missing here,
    // so the drift cannot come back silently.
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "**/cdk.out/**",
      "**/cdk.out.test/**",
      // Next.js build output (`apps/developer-portal/.gitignore`): `.next` is the incremental
      // build, `out` the static export. Both hold minified bundles; no tracked source lives there.
      "**/.next/**",
      "**/out/**",
      // Nested git worktrees created for parallel agent runs. Each is a full checkout of the
      // repository, so linting them double-counts every file and is local-only state.
      ".claude/worktrees/**",
      // Repo-sanctioned scratch directory (`.gitignore:170`). Its contents are untracked, so
      // linting it makes the file set differ per machine.
      "tmp/**",
      // Generated by `next build` and git-ignored, so it exists locally but not in CI at lint
      // time. It reports nothing today, but linting a file only one side of the gate has means
      // any future violation in it would enter the ceiling and CI could never reproduce it.
      "**/next-env.d.ts",
      "landing/**",
      "problems/**",
    ],
  },
  ...tseslint.configs.strict,
  ...tseslint.configs.stylistic,
  sonarjs.configs.recommended,
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    rules: {
      // #2861 set `assertionStyle: "never"` (= ban every `as`) on a gate that never ran. When it
      // first executed (#2862) it produced 105 findings across 43 files, all of them narrowing at
      // an external boundary: `JSON.parse`, `await response.json()`, `querySelector`, and generic
      // `as T` helpers. Satisfying "never" means a runtime-validation layer across all of
      // scripts/, which is a different piece of work — and until then the gate can never be green,
      // so `make before-commit` and CI would be permanently red for every PR.
      // "as" is typescript-eslint's documented default and still bans the angle-bracket form;
      // `objectLiteralTypeAssertions: "never"` keeps the assertion that actually hides bugs
      // (`{...} as T` silently accepts a missing property) banned. It caught one live instance.
      "@typescript-eslint/consistent-type-assertions": [
        "error",
        { assertionStyle: "as", objectLiteralTypeAssertions: "never" },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/ban-ts-comment": "error",
      // `_` prefix is this repo's existing "intentionally unused" marker (rest-sibling omit
      // idiom, interface-mandated parameters). Without an ignore pattern the rule has no way to
      // express that, so it reported deliberate placeholders. An *unprefixed* unused binding is
      // still an error — this narrows the rule's vocabulary, not its reach.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          // `const { secret, ...rest } = x` is the omit idiom, not a dead binding.
          // sonarjs/no-unused-vars recognises it only in this shorthand form, so both rules
          // have to agree on it or the two contradict each other.
          ignoreRestSiblings: true,
        },
      ],
      // no-floating-promises requires `void promise` for intentionally detached
      // work, so Sonar's blanket ban would make the two rules contradictory.
      "sonarjs/void-use": "off",
    },
  },
  {
    files: typedSourceFiles,
    ignores: testFiles,
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        // Type-aware lint needs every linted file to belong to the program. `tsconfig.scripts.json`
        // is the *typecheck gate* scope and #2861 narrowed it to a single file, so sharing it made
        // the parser reject every other script with "The file was not found in any of the provided
        // project(s)" (#2862 — 97 of the 148 findings). Lint therefore gets its own project that
        // inherits the same compilerOptions but spans all of scripts/.
        //
        // That project additionally turns on `noUncheckedIndexedAccess`, which the typecheck gate
        // does not: without it `argv[i]` is typed `string`, so sonarjs/different-types-comparison
        // called four real `=== undefined` guards over argv / split() results dead code. The flag
        // only makes the lint program's types *less* optimistic and adds no findings of its own.
        project: ["./tsconfig.eslint.json"],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-floating-promises": "warn",
      "@typescript-eslint/no-misused-promises": "warn",
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/no-base-to-string": "error",
    },
  },
];
