/**
 * [Composite Runtime / Issue #2061] Repository for composite parent + per-target
 * deployment rows.
 *
 * Storage / persistence only — this module does NOT start deployments, publish
 * EventBridge events, invoke adapters, aggregate state, or touch the HTTP API.
 * It persists a parent coordination row and N independent target rows, and reads
 * them back (a parent, a single target, or a parent's targets in ordinal order).
 *
 * Dependencies are injected (`ddb` + `tableName`); the repository never
 * constructs a DynamoDB client itself.
 *
 * Idempotency / conflict semantics (issue #2061):
 *   - Re-writing a target with the same `targetDeploymentId` and identical
 *     immutable fields is a no-op success.
 *   - Re-writing the same `targetDeploymentId` with different immutable fields
 *     (parent / targetId / ordinal / provider / engine / entry) fails loudly.
 *   - Two different `targetDeploymentId`s sharing a `targetId` under the same
 *     parent fail loudly; the same `targetId` under a different parent is fine.
 *   - Creating the parent and each target is not one transaction. Partial state
 *     (parent + targets 0..N-1) is left observable; no status mutation, no
 *     cleanup.
 */

import {
  type DynamoDBDocumentClient,
  GetCommand,
  PutCommand,
  QueryCommand,
} from "@aws-sdk/lib-dynamodb";
import {
  COMPOSITE_RUNTIME_KIND,
  COMPOSITE_VERSION,
  type CompositeParentDeploymentItem,
  type CompositeTargetDeploymentItem,
  compositeTargetGsi3Pk,
  compositeTargetGsi3Sk,
  deploymentPk,
  isCompositeParentItem,
  isCompositeTargetItem,
  MAX_COMPOSITE_TARGETS,
  MIN_COMPOSITE_TARGETS,
} from "./composite-deployment.js";
import type { DeploymentStatus } from "./types.js";

const GSI3_INDEX_NAME = "GSI3";
const CONDITION_PK_ABSENT = "attribute_not_exists(PK)";

/** Injected dependencies. The `ddb` client is created by the caller, not here. */
export interface CompositeDeploymentRepositoryDeps {
  readonly ddb: Pick<DynamoDBDocumentClient, "send">;
  readonly tableName: string;
}

/** Raised when a target write conflicts with an already-persisted row. */
export class CompositeTargetConflictError extends Error {
  constructor(
    public readonly targetDeploymentId: string,
    public readonly reason: string,
  ) {
    super(`composite target ${targetDeploymentId} conflict: ${reason}`);
    this.name = "CompositeTargetConflictError";
  }
}

/** Raised when a parent write conflicts with an already-persisted parent row. */
export class CompositeParentConflictError extends Error {
  constructor(
    public readonly parentDeploymentId: string,
    public readonly reason: string,
  ) {
    super(`composite parent ${parentDeploymentId} conflict: ${reason}`);
    this.name = "CompositeParentConflictError";
  }
}

export interface CreateCompositeParentInput {
  readonly parentDeploymentId: string;
  readonly tenantId: string;
  readonly problemId: string;
  /** 2..8 — mirrors the composite metadata target count. */
  readonly targetCount: number;
  readonly createdAt: string;
  readonly updatedAt?: string;
  readonly expiresAt: number;
  readonly status?: DeploymentStatus;
  /** [#2063] Team identity shared across the parent + every target row. */
  readonly teamName?: string;
  readonly teamLoginKey?: string;
}

export interface CreateCompositeTargetInput {
  /** Globally unique id generated by the caller; becomes the row's `DEPLOYMENT#{id}`. */
  readonly targetDeploymentId: string;
  readonly parentDeploymentId: string;
  readonly targetId: string;
  readonly targetOrdinal: number;
  readonly tenantId: string;
  readonly problemId: string;
  readonly provider: string;
  readonly engine: string;
  readonly entry: string;
  readonly awsAccountId: string;
  readonly region: string;
  readonly teamName: string;
  readonly namePrefix: string;
  readonly teamLoginKey: string;
  readonly createdAt: string;
  readonly updatedAt?: string;
  readonly expiresAt: number;
  readonly status?: DeploymentStatus;
  readonly competitorRoleArn?: string;
  readonly externalIdParameterName?: string;
  readonly displayTeamName?: string;
}

function isConditionalCheckFailed(err: unknown): boolean {
  return (err as { name?: string } | undefined)?.name === "ConditionalCheckFailedException";
}

/**
 * Create the composite parent coordination row. Idempotent: re-creating with the
 * same immutable identity (tenant / problem / targetCount) returns the existing
 * row; a divergent re-create fails with {@link CompositeParentConflictError}.
 */
export async function createCompositeParent(
  deps: CompositeDeploymentRepositoryDeps,
  input: CreateCompositeParentInput,
): Promise<CompositeParentDeploymentItem> {
  if (
    !Number.isInteger(input.targetCount) ||
    input.targetCount < MIN_COMPOSITE_TARGETS ||
    input.targetCount > MAX_COMPOSITE_TARGETS
  ) {
    throw new RangeError(
      `composite targetCount must be an integer in [${MIN_COMPOSITE_TARGETS}, ${MAX_COMPOSITE_TARGETS}], got ${input.targetCount}`,
    );
  }

  const item: CompositeParentDeploymentItem = {
    PK: deploymentPk(input.parentDeploymentId),
    SK: "META",
    jobId: input.parentDeploymentId,
    tenantId: input.tenantId,
    problemId: input.problemId,
    runtimeKind: COMPOSITE_RUNTIME_KIND,
    compositeVersion: COMPOSITE_VERSION,
    targetCount: input.targetCount,
    status: input.status ?? "PENDING",
    createdAt: input.createdAt,
    updatedAt: input.updatedAt ?? input.createdAt,
    expiresAt: input.expiresAt,
    ...(input.teamName ? { teamName: input.teamName } : {}),
    ...(input.teamLoginKey ? { teamLoginKey: input.teamLoginKey } : {}),
  };

  try {
    await deps.ddb.send(
      new PutCommand({
        TableName: deps.tableName,
        Item: item,
        ConditionExpression: CONDITION_PK_ABSENT,
      }),
    );
    return item;
  } catch (err) {
    if (!isConditionalCheckFailed(err)) throw err;
    const existing = await getCompositeParent(deps, input.parentDeploymentId);
    if (
      existing &&
      existing.tenantId === item.tenantId &&
      existing.problemId === item.problemId &&
      existing.targetCount === item.targetCount
    ) {
      return existing;
    }
    throw new CompositeParentConflictError(
      input.parentDeploymentId,
      "a different parent row already exists at this id",
    );
  }
}

/**
 * Create one composite target row. See module docs for idempotency / conflict
 * rules. Creates the parent's targets one at a time (the caller drives ordinal
 * order); a per-write target-id uniqueness check scopes to the parent.
 */
export async function createCompositeTarget(
  deps: CompositeDeploymentRepositoryDeps,
  input: CreateCompositeTargetInput,
): Promise<CompositeTargetDeploymentItem> {
  if (!Number.isInteger(input.targetOrdinal) || input.targetOrdinal < 0) {
    throw new RangeError(
      `composite targetOrdinal must be a non-negative integer, got ${input.targetOrdinal}`,
    );
  }

  const item = buildCompositeTargetItem(input);

  // 1. A row already at this targetDeploymentId → idempotent if immutables match,
  //    otherwise a loud conflict (never a silent overwrite).
  const existing = await getRawRow(deps, input.targetDeploymentId);
  if (existing) {
    if (!isCompositeTargetItem(existing)) {
      throw new CompositeTargetConflictError(
        input.targetDeploymentId,
        "a non-composite-target row already exists at this id",
      );
    }
    if (immutableTargetFieldsMatch(existing, item)) return item;
    throw new CompositeTargetConflictError(
      input.targetDeploymentId,
      "an existing target row has different immutable fields",
    );
  }

  // 2. targetId must be unique within the parent (a different deploymentId reusing
  //    the same targetId under the same parent is a conflict).
  const siblings = await listCompositeTargets(deps, input.parentDeploymentId);
  const clash = siblings.find(
    (sibling) => sibling.targetId === input.targetId && sibling.PK !== item.PK,
  );
  if (clash) {
    throw new CompositeTargetConflictError(
      input.targetDeploymentId,
      `targetId ${input.targetId} already used by ${clash.jobId} under parent ${input.parentDeploymentId}`,
    );
  }

  // 3. Persist, guarding against a concurrent writer racing the same PK.
  try {
    await deps.ddb.send(
      new PutCommand({
        TableName: deps.tableName,
        Item: item,
        ConditionExpression: CONDITION_PK_ABSENT,
      }),
    );
  } catch (err) {
    if (isConditionalCheckFailed(err)) {
      throw new CompositeTargetConflictError(
        input.targetDeploymentId,
        "a row was created concurrently at this id",
      );
    }
    throw err;
  }
  return item;
}

/** Read a composite parent row, or undefined if absent / not a parent row. */
export async function getCompositeParent(
  deps: CompositeDeploymentRepositoryDeps,
  parentDeploymentId: string,
): Promise<CompositeParentDeploymentItem | undefined> {
  const row = await getRawRow(deps, parentDeploymentId);
  return isCompositeParentItem(row) ? row : undefined;
}

/** Read a composite target row, or undefined if absent / not a target row. */
export async function getCompositeTarget(
  deps: CompositeDeploymentRepositoryDeps,
  targetDeploymentId: string,
): Promise<CompositeTargetDeploymentItem | undefined> {
  const row = await getRawRow(deps, targetDeploymentId);
  return isCompositeTargetItem(row) ? row : undefined;
}

/**
 * List a parent's target rows in targetOrdinal order via GSI3. Returns whatever
 * targets currently exist — partial creation is observable, not hidden.
 */
export async function listCompositeTargets(
  deps: CompositeDeploymentRepositoryDeps,
  parentDeploymentId: string,
): Promise<CompositeTargetDeploymentItem[]> {
  const out = await deps.ddb.send(
    new QueryCommand({
      TableName: deps.tableName,
      IndexName: GSI3_INDEX_NAME,
      KeyConditionExpression: "GSI3PK = :pk",
      ExpressionAttributeValues: { ":pk": compositeTargetGsi3Pk(parentDeploymentId) },
      ScanIndexForward: true,
    }),
  );
  return (out.Items ?? []).filter(isCompositeTargetItem);
}

async function getRawRow(
  deps: CompositeDeploymentRepositoryDeps,
  deploymentId: string,
): Promise<Record<string, unknown> | undefined> {
  const out = await deps.ddb.send(
    new GetCommand({
      TableName: deps.tableName,
      Key: { PK: deploymentPk(deploymentId), SK: "META" },
    }),
  );
  return out.Item as Record<string, unknown> | undefined;
}

function buildCompositeTargetItem(
  input: CreateCompositeTargetInput,
): CompositeTargetDeploymentItem {
  return {
    PK: deploymentPk(input.targetDeploymentId),
    SK: "META",
    jobId: input.targetDeploymentId,
    problemId: input.problemId,
    tenantId: input.tenantId,
    awsAccountId: input.awsAccountId,
    region: input.region,
    teamName: input.teamName,
    namePrefix: input.namePrefix,
    teamLoginKey: input.teamLoginKey,
    status: input.status ?? "PENDING",
    createdAt: input.createdAt,
    updatedAt: input.updatedAt ?? input.createdAt,
    expiresAt: input.expiresAt,
    parentDeploymentId: input.parentDeploymentId,
    targetId: input.targetId,
    targetOrdinal: input.targetOrdinal,
    runtimeProvider: input.provider,
    runtimeEngine: input.engine,
    runtimeEntry: input.entry,
    GSI3PK: compositeTargetGsi3Pk(input.parentDeploymentId),
    GSI3SK: compositeTargetGsi3Sk(input.targetOrdinal, input.targetId),
    ...(input.competitorRoleArn ? { competitorRoleArn: input.competitorRoleArn } : {}),
    ...(input.externalIdParameterName
      ? { externalIdParameterName: input.externalIdParameterName }
      : {}),
    ...(input.displayTeamName ? { displayTeamName: input.displayTeamName } : {}),
  };
}

function immutableTargetFieldsMatch(
  existing: CompositeTargetDeploymentItem,
  next: CompositeTargetDeploymentItem,
): boolean {
  return (
    existing.parentDeploymentId === next.parentDeploymentId &&
    existing.targetId === next.targetId &&
    existing.targetOrdinal === next.targetOrdinal &&
    existing.runtimeProvider === next.runtimeProvider &&
    existing.runtimeEngine === next.runtimeEngine &&
    existing.runtimeEntry === next.runtimeEntry
  );
}
