import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  assertReleaseCheckEligible,
  type ReleaseManifest,
  type ReleaseSourceRef,
  readReleaseManifest,
} from "./manifest";

export const RELEASE_REPORT_PATH = resolve(
  import.meta.dirname,
  "../../release/tenkacloud-release.md",
);

function markdownCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", "<br>");
}

function repositoryBrowserUrl(repository: string): string {
  return repository.endsWith(".git") ? repository.slice(0, -4) : repository;
}

function sourceLink(source: ReleaseSourceRef): string {
  const commitUrl = `${repositoryBrowserUrl(source.repository)}/commit/${source.commit}`;
  const codeQuote = "`";
  return `[${codeQuote}${source.commit}${codeQuote}](${commitUrl})`;
}

function statusSummary(manifest: ReleaseManifest): string {
  if (manifest.release.status === "certified") {
    return "Structurally certification-eligible, not publishable as certified: every declared mode and region has three consecutive BOM-bound Golden Path runs with distinct fresh-environment evidence and a passed residual-scanner-v1 report, but the #2982 artifact resolver gate is still required.";
  }
  return "Candidate / unverified: this manifest pins the catalog, Simulator, and toolchain of the next release, but it is not certified for any mode or region.";
}

function qualificationSection(manifest: ReleaseManifest): string {
  const rows = manifest.compatibility.qualificationTargets
    .map(({ mode, regions }) => `| ${mode} | ${regions.map(markdownCell).join(", ")} |`)
    .join("\n");
  return `| Mode | Qualification regions (not a support claim) |\n| --- | --- |\n${rows}`;
}

function compatibilitySection(manifest: ReleaseManifest): string {
  if (manifest.compatibility.supportedModes.length === 0) {
    return "No deployment modes or AWS regions are certified by this candidate manifest.";
  }
  const rows = manifest.compatibility.supportedModes
    .map(({ mode, regions }) => `| ${mode} | ${regions.map(markdownCell).join(", ")} |`)
    .join("\n");
  return `| Mode | Certified regions |\n| --- | --- |\n${rows}`;
}

function verificationSection(manifest: ReleaseManifest): string {
  if (manifest.verification.goldenPathRuns.length === 0) {
    return "No Golden Path run is attached. Three consecutive runs bound to this exact BOM must pass with distinct fresh-environment evidence, immutable runner identity, and distinct digest-pinned Golden Path plus passed residual-scanner-v1 reports for each supported mode and region before certification.";
  }
  const rows = manifest.verification.goldenPathRuns
    .map(
      (run) =>
        `| ${markdownCell(run.runId)} | ${run.mode} | ${run.region} | ${run.completedAt} | ${run.result} | [${markdownCell(run.freshEnvironment.environmentId)}: ${run.freshEnvironment.decision}](${run.freshEnvironment.evidenceUrl}) (\`sha256:${run.freshEnvironment.evidenceSha256}\`) | [Golden Path](${run.evidenceUrl}) (\`sha256:${run.evidenceSha256}\`) | [${run.residualScan.decision}](${run.residualScan.evidenceUrl}) (\`sha256:${run.residualScan.evidenceSha256}\`) | [${run.runner.commit.slice(0, 12)}](${repositoryBrowserUrl(run.runner.repository)}/commit/${run.runner.commit}) | exact top-level BOM |`,
    )
    .join("\n");
  return `| Run ID | Mode | Region | Completed | Result | Fresh environment | Digest-pinned run evidence | Residual scanner v1 | Verification runner | BOM binding |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n${rows}`;
}

/** Deterministic human view of the machine-readable release manifest. */
export function renderReleaseReport(manifest: ReleaseManifest): string {
  const reportTitle =
    manifest.release.status === "candidate"
      ? `TenkaCloud release candidate ${manifest.release.version}`
      : `TenkaCloud release ${manifest.release.version}`;
  const catalogTag = manifest.sources.catalog.tag
    ? `\`${markdownCell(manifest.sources.catalog.tag)}\``
    : "—";
  const platformRepository = repositoryBrowserUrl(manifest.sources.platform.repository);
  const contractRows = manifest.compatibility.contracts
    .map(({ id, version }) => `| ${markdownCell(id)} | \`${markdownCell(version)}\` |`)
    .join("\n");
  const limitations = manifest.knownLimitations
    .map((limitation) => `- ${limitation.replaceAll("\n", " ")}`)
    .join("\n");

  return `<!-- Generated by scripts/release/generate-release-report.ts. Do not edit. -->

# ${reportTitle}

> ${statusSummary(manifest)}

The machine-readable source of truth is [\`tenkacloud-release.json\`](./tenkacloud-release.json), validated against [\`tenkacloud-release.schema.json\`](./tenkacloud-release.schema.json). Tags are display labels; the full commit and image digest below are authoritative.

> Publication gate: schema and semantic validation alone do not authenticate downloaded evidence bytes. \`release:check\` rejects \`certified\` until #2982 verifies every referenced artifact's schema and SHA-256 digest.

## Immutable release identity

| Component | Authoritative reference | Display tag |
| --- | --- | --- |
| Platform | [${platformRepository}](${platformRepository}) — the commit tagged \`v${manifest.release.version}\` | — |
| Problem catalog | ${sourceLink(manifest.sources.catalog)} | ${catalogTag} |
| Simulator | \`${manifest.artifacts.simulatorImage}\` | — |

The platform commit is derived from the release tag at publish time (\`scripts/release/verify-release-identity.ts\`, #3024): this manifest is part of the tagged tree, so it cannot record the SHA of the commit that contains it. Until the tag exists, the platform identity of this manifest is the in-progress branch it ships on.

## Toolchain

| Component | Version |
| --- | --- |
| Bun | \`${manifest.toolchain.bun}\` |
| Node.js (development) | \`${manifest.toolchain.node.development}\` |
| Node.js (Lite launcher) | \`${manifest.toolchain.node.launcher}\` |
| AWS CDK CLI | \`${manifest.toolchain.awsCdk.cli}\` |
| AWS CDK library | \`${manifest.toolchain.awsCdk.library}\` |

## Qualification targets

${qualificationSection(manifest)}

These targets may collect partial or failed evidence while the release remains a candidate. Only the next section is a certification claim.

## Certified compatibility

${compatibilitySection(manifest)}

### Schema and migration contracts

Contract versions are named per subsystem; TenkaCloud does not claim a single global database schema version.

| Contract | Version |
| --- | --- |
${contractRows}

## Golden Path verification

${verificationSection(manifest)}

## Known limitations

${limitations || "No known limitations are recorded."}
`;
}

/** The exact render path used by `release:check`, including the #2982 publication stop. */
export function renderReleaseReportForCheck(manifest: ReleaseManifest): string {
  assertReleaseCheckEligible(manifest);
  return renderReleaseReport(manifest);
}

export function generateReleaseReport(): string {
  return renderReleaseReport(readReleaseManifest());
}

function main(): void {
  const check = process.argv.includes("--check");
  const manifest = readReleaseManifest();
  const next = check ? renderReleaseReportForCheck(manifest) : renderReleaseReport(manifest);
  if (check) {
    const current = existsSync(RELEASE_REPORT_PATH)
      ? readFileSync(RELEASE_REPORT_PATH, "utf8")
      : "";
    if (current !== next) {
      console.error(
        "Release report is missing or stale. Run " +
          "'bun run scripts/release/generate-release-report.ts' and commit the result.",
      );
      process.exit(1);
    }
    console.log("Release report is up to date with tenkacloud-release.json.");
    return;
  }
  writeFileSync(RELEASE_REPORT_PATH, next);
  console.log(`Wrote ${RELEASE_REPORT_PATH}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
