/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a1eddf0604f758529a4404fe916081b2)
interface __BaseEnv_Env {
  CONTROL_DB: D1Database;
  AUTH0_ISSUER: "https://replace-me-staging.auth0.com/" | "https://replace-me.auth0.com/";
  AUTH0_AUDIENCE: "https://staging-api.tenkacloud.dev" | "https://api.tenkacloud.dev";
  AUTH0_CLIENT_ID: "replace-me-staging" | "replace-me";
  AUTH0_ROLES_CLAIM: "https://tenkacloud.dev/roles";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface StagingEnv {
    CONTROL_DB: D1Database;
    AUTH0_ISSUER: "https://replace-me-staging.auth0.com/";
    AUTH0_AUDIENCE: "https://staging-api.tenkacloud.dev";
    AUTH0_CLIENT_ID: "replace-me-staging";
    AUTH0_ROLES_CLAIM: "https://tenkacloud.dev/roles";
  }
  interface ProductionEnv {
    CONTROL_DB: D1Database;
    AUTH0_ISSUER: "https://replace-me.auth0.com/";
    AUTH0_AUDIENCE: "https://api.tenkacloud.dev";
    AUTH0_CLIENT_ID: "replace-me";
    AUTH0_ROLES_CLAIM: "https://tenkacloud.dev/roles";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        "AUTH0_ISSUER" | "AUTH0_AUDIENCE" | "AUTH0_CLIENT_ID" | "AUTH0_ROLES_CLAIM"
      >
    > {}
}
