/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4e4bed2cd71595362add8c11d114c64b)
interface __BaseEnv_Env {
  CONTROL_DB: D1Database;
  AUTH0_ISSUER: "https://replace-me-staging.auth0.com/" | "https://replace-me.auth0.com/";
  AUTH0_AUDIENCE: "https://staging-api.tenkacloud.dev" | "https://api.tenkacloud.dev";
  AUTH0_CLIENT_ID: "replace-me-staging" | "replace-me";
  AUTH0_ROLES_CLAIM: "https://tenkacloud.dev/roles";
  MCP_CANONICAL_ORIGIN:
    | "https://replace-me-staging.example.invalid"
    | "https://replace-me.example.invalid"
    | "http://localhost:8787";
  COMMAND_ROLE_ARN: "arn:aws:iam::000000000000:role/tenkacloud-alwayson-command";
  COMMAND_AWS_REGION: "ap-northeast-1";
  COMMAND_EVENT_BUS_ARN: "arn:aws:events:ap-northeast-1:000000000000:event-bus/replace-me";
  PROBLEMS_CATALOG: "{}";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface StagingEnv {
    CONTROL_DB: D1Database;
    AUTH0_ISSUER: "https://replace-me-staging.auth0.com/";
    AUTH0_AUDIENCE: "https://staging-api.tenkacloud.dev";
    AUTH0_CLIENT_ID: "replace-me-staging";
    AUTH0_ROLES_CLAIM: "https://tenkacloud.dev/roles";
    MCP_CANONICAL_ORIGIN: "https://replace-me-staging.example.invalid";
    COMMAND_ROLE_ARN: "arn:aws:iam::000000000000:role/tenkacloud-alwayson-command";
    COMMAND_AWS_REGION: "ap-northeast-1";
    COMMAND_EVENT_BUS_ARN: "arn:aws:events:ap-northeast-1:000000000000:event-bus/replace-me";
    PROBLEMS_CATALOG: "{}";
  }
  interface ProductionEnv {
    CONTROL_DB: D1Database;
    AUTH0_ISSUER: "https://replace-me.auth0.com/";
    AUTH0_AUDIENCE: "https://api.tenkacloud.dev";
    AUTH0_CLIENT_ID: "replace-me";
    AUTH0_ROLES_CLAIM: "https://tenkacloud.dev/roles";
    MCP_CANONICAL_ORIGIN: "https://replace-me.example.invalid";
    COMMAND_ROLE_ARN: "arn:aws:iam::000000000000:role/tenkacloud-alwayson-command";
    COMMAND_AWS_REGION: "ap-northeast-1";
    COMMAND_EVENT_BUS_ARN: "arn:aws:events:ap-northeast-1:000000000000:event-bus/replace-me";
    PROBLEMS_CATALOG: "{}";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "AUTH0_ISSUER"
        | "AUTH0_AUDIENCE"
        | "AUTH0_CLIENT_ID"
        | "AUTH0_ROLES_CLAIM"
        | "MCP_CANONICAL_ORIGIN"
        | "COMMAND_ROLE_ARN"
        | "COMMAND_AWS_REGION"
        | "COMMAND_EVENT_BUS_ARN"
        | "PROBLEMS_CATALOG"
      >
    > {}
}
