/**
 * Issue #1910 Slice 5: 問題ごとの「使用 AWS リソース + 概算コスト」を GitHub 上に出す
 * カタログ markdown を組み立てる純関数群。 I/O (問題探索 / ファイル書き込み) は
 * `scripts/build-cost-catalog.ts` 側が持ち、 ここは entry 配列 → markdown の決定的変換に専念する
 * (= unit test しやすく、 submodule の中身に依存しない)。
 *
 * コスト値は `scripts/lib/problem-cost.ts` の offline / deterministic な heuristic 由来で、
 * 課金保証ではない (= 初見ユーザー向けの概算)。
 */
import { formatUsd, type ProblemCostEstimate } from "./problem-cost";

export interface CostCatalogEntry {
  readonly id: string;
  readonly name: string;
  readonly category: string;
  readonly estimatedDuration: string;
  readonly estimate: ProblemCostEstimate;
}

/** `AWS::` prefix を落とした短縮表記にする (= 一覧の横幅圧縮)。 */
function shortType(resourceType: string): string {
  return resourceType.replace(/^AWS::/, "");
}

function uniqueSorted(values: readonly string[]): readonly string[] {
  return [...new Set(values)].sort();
}

/** template に含まれる AWS リソース型の重複排除済み・ソート済み短縮表記。 */
export function resourceTypesUsed(estimate: ProblemCostEstimate): readonly string[] {
  return uniqueSorted(estimate.resources.map((resource) => shortType(resource.resourceType)));
}

/** teardown まで課金され続ける always-on リソース型 (standing cost) の短縮表記。 */
export function alwaysOnTypesUsed(estimate: ProblemCostEstimate): readonly string[] {
  return uniqueSorted(
    estimate.alwaysOnWarnings.map((resource) => shortType(resource.resourceType)),
  );
}

/**
 * markdown table cell 内で意味を持つ文字をエスケープする。 `\` を先に `\\` へ逃がしてから
 * `|` を `\|` にする (= backslash を先に処理しないと escaping が不完全になる)。
 */
function escapeCell(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\|/g, "\\|");
}

function listOrDash(values: readonly string[]): string {
  return values.length > 0 ? escapeCell(values.join(", ")) : "—";
}

const HEADER = [
  "Problem",
  "Category",
  "Est. play time",
  "AWS resources used",
  "Cost/hr",
  "Cost/play",
  "Per day if left running",
  "Always-on",
] as const;

function renderRow(entry: CostCatalogEntry): string {
  const cells = [
    `${escapeCell(entry.name)} (\`${escapeCell(entry.id)}\`)`,
    escapeCell(entry.category),
    escapeCell(entry.estimatedDuration),
    listOrDash(resourceTypesUsed(entry.estimate)),
    formatUsd(entry.estimate.totalHourlyUsd),
    formatUsd(entry.estimate.perSessionUsd),
    formatUsd(entry.estimate.perDayIfLeftRunningUsd),
    listOrDash(alwaysOnTypesUsed(entry.estimate)),
  ];
  return `| ${cells.join(" | ")} |`;
}

/**
 * entry 配列を id 昇順の決定的 markdown に変換する。 timestamp は埋め込まない
 * (= `--check` の drift 検出が壊れないように)。
 */
export function renderCostCatalog(entries: readonly CostCatalogEntry[]): string {
  const sorted = [...entries].sort((a, b) => a.id.localeCompare(b.id));
  const alwaysOnCount = sorted.filter(
    (entry) => alwaysOnTypesUsed(entry.estimate).length > 0,
  ).length;
  const lines = [
    "# Problem cost catalog",
    "",
    "Per-problem AWS resources and a rough, offline cost estimate, derived from each problem's",
    "`template.yaml` via the cost model in `scripts/lib/problem-cost.ts`. Figures are deterministic",
    "ballpark numbers for first-time-user reassurance, not a billing guarantee. This file is",
    "generated by `scripts/build-cost-catalog.ts`; regenerate with `make cost-catalog` (then",
    "`make build-docs` for the HTML).",
    "",
    `This catalog covers ${sorted.length} problem(s); ${alwaysOnCount} contain always-on`,
    "(standing-cost) resources that keep billing until teardown.",
    "",
    `| ${HEADER.join(" | ")} |`,
    `| ${HEADER.map(() => "---").join(" | ")} |`,
    ...sorted.map(renderRow),
    "",
  ];
  return lines.join("\n");
}
