/**
 * Issues #2291 and #642: private-problem payload fetch for the Lambda deploy path.
 *
 * The Lambda deploy path ({@link ./handlers/cfn-deploy-handler/create-stack.ts | create-stack.ts})
 * normally reads `template.yaml` + `metadata.json` straight from the materialized `problems/` tree
 * in the source bucket (public problems). For **private** problems the tree is not materialized;
 * instead the deploy event carries a short-lived (15-min TTL) presigned S3 URL to a `payload.zip`
 * (`challengePayloadUrl`, generated by `deploy-handler/visibility.ts`). This module is the HTTP +
 * unzip primitive that consumes that URL — the TypeScript equivalent of the
 * `resolve_problem_dir()` block in `scripts/deploy-battles.sh` (curl the presigned URL → unzip →
 * find the dir that contains `template.yaml` → use its sibling `metadata.json`).
 *
 * ## Placement (harness invariant)
 *
 * This lives **outside** `lib/handlers/` on purpose: the `handler-must-not-call-fetch` rule forbids
 * a raw `fetch(` under any `.../handlers/...` path. The HTTP primitive is injected into the handler
 * (create-stack.ts wires the real fn; tests inject a fake), keeping the handler mockable and this
 * one call site the only place a raw fetch appears.
 *
 * ## Security bounds (each mirrors a threat this consumer must contain)
 *
 * The presigned URL is minted by our own backend from our own validated event detail
 * (`z.string().url()`), so this is not attacker-controlled free-text in the normal threat model.
 * The bounds below are defense-in-depth for a compromised / malformed payload:
 *
 *   (a) {@link MAX_PAYLOAD_BYTES} caps the **downloaded (compressed) bytes BEFORE unzip**, bounding
 *       the zip-bomb blast radius at its input. Enforced twice: the default `httpGet` rejects on a
 *       `Content-Length` over the cap (early, no full download), and the orchestrator re-checks the
 *       actual byte length after `httpGet` returns so an injected fetcher is bounded too.
 *   (b) The `unzipSync` `filter` inflates ONLY the two entries we read (`template.yaml` /
 *       `metadata.json`) and only if the zip header declares each within {@link MAX_ENTRY_BYTES} —
 *       the check runs per-entry BEFORE decompression, so a zip-bomb in a non-target (or over-cap)
 *       entry is never inflated. {@link MAX_DECOMPRESSED_BYTES} + {@link MAX_ENTRY_COUNT} are
 *       backstops on that small filtered set. (Residual: a target entry whose header understates its
 *       true size could still inflate; the compressed cap (a) + first-party payload bound that
 *       narrow self-DoS — the deploy Lambda would OOM that one job, loud-fail, no breach.)
 *   (c) We only READ two named in-memory entries (`template.yaml` + its sibling `metadata.json`).
 *       We never extract to the filesystem, so there is no zip-slip / path-traversal write risk.
 *   (d) A non-2xx HTTP response is rejected (fail loud), never treated as an empty payload.
 *   (e) `redirect: "error"` — a presigned S3 GET returns the object directly (200), so we refuse to
 *       follow a redirect to a different host/scheme (SSRF-via-redirect hardening).
 *
 * No secret is logged here (the presigned URL carries a signature): this module emits no logs and
 * never includes the URL in an error message.
 *
 * [Issue #2745] {@link fetchChallengePayloadDirectory} extends the same bounded fetch + unzip
 * primitive to pull an arbitrary DIRECTORY of files out of the payload — a Terraform /
 * Infrastructure Manager root module is usually several files (`main.tf`, `variables.tf`, ...),
 * unlike the two fixed filenames above. It shares {@link defaultHttpGet} and the same zip-bomb
 * bounds (a)-(b); only the entry filter and the returned shape differ (an unbounded set of
 * `{relativePath, bytes}` files instead of two named strings).
 */

import { unzipSync } from "fflate";

/** Filename of the CloudFormation deploy body inside a problem payload (3-asset model). */
const TEMPLATE_ENTRY = "template.yaml" as const;
/** Filename of the problem metadata (source of the `cfnParameters`). */
const METADATA_ENTRY = "metadata.json" as const;

/**
 * (a) Hard cap on the downloaded (compressed) payload before unzip. 25 MiB is far above a real
 * problem payload (a `template.yaml` + `metadata.json` + optional `portal/*.tsx`) while bounding the
 * zip-bomb input.
 */
export const MAX_PAYLOAD_BYTES = 25 * 1024 * 1024;

/**
 * (b) Per-entry cap on the **declared uncompressed size** (from the zip's directory header), applied
 * inside {@link unzipSync}'s `filter` so an over-cap entry is rejected BEFORE it is inflated. A real
 * `template.yaml` / `metadata.json` is a few KiB; 10 MiB is generous. This is the primary decompress
 * bound: combined with the name filter (only the two target entries are inflated at all), a zip-bomb
 * hidden in extra entries never decompresses, and an oversized target entry is skipped pre-inflation.
 */
export const MAX_ENTRY_BYTES = 10 * 1024 * 1024;

/**
 * (b) Backstop cap on the summed decompressed size of the entries we actually inflate (the two
 * target files). Because the `filter` already skips non-target and over-{@link MAX_ENTRY_BYTES}
 * entries, this only ever sums the small template + metadata; it is a defensive re-check, not the
 * primary bound.
 */
export const MAX_DECOMPRESSED_BYTES = 100 * 1024 * 1024;

/**
 * (b) Cap on the number of inflated (filter-matched) entries — bounds a payload that packs many
 * nested `template.yaml` / `metadata.json` entries to force repeated inflation.
 */
export const MAX_ENTRY_COUNT = 512;

export interface ChallengePayloadArtifacts {
  readonly templateBody: string;
  readonly metadataText: string;
}

export interface FetchChallengePayloadDeps {
  /**
   * HTTP GET the presigned URL and return the raw bytes. Defaults to {@link defaultHttpGet} (global
   * `fetch`); injected as a fake in unit tests so no real network is touched.
   */
  readonly httpGet?: (url: string) => Promise<Uint8Array>;
  /** Override the compressed-size cap (a) — for tests; defaults to {@link MAX_PAYLOAD_BYTES}. */
  readonly maxPayloadBytes?: number;
  /** Override the decompressed-size cap (b) — for tests; defaults to {@link MAX_DECOMPRESSED_BYTES}. */
  readonly maxDecompressedBytes?: number;
  /** Override the entry-count cap (b) — for tests; defaults to {@link MAX_ENTRY_COUNT}. */
  readonly maxEntryCount?: number;
  /** Override the per-entry declared-size cap (b) — for tests; defaults to {@link MAX_ENTRY_BYTES}. */
  readonly maxEntryBytes?: number;
}

/** The two payload files the deploy reads: `template.yaml` / `metadata.json`, at any dir depth. */
function isTargetEntry(name: string): boolean {
  return (
    name === TEMPLATE_ENTRY ||
    name.endsWith(`/${TEMPLATE_ENTRY}`) ||
    name === METADATA_ENTRY ||
    name.endsWith(`/${METADATA_ENTRY}`)
  );
}

/**
 * Default HTTP primitive: a plain HTTPS GET of the self-authorizing presigned S3 URL (no AWS SDK,
 * no new IAM — mirrors `curl` in the shell path). Rejects a non-2xx response (d) and refuses to
 * follow a redirect (e). Rejects early on a `Content-Length` over `maxBytes` (a); the byte length is
 * re-checked by the caller after this returns.
 */
async function defaultHttpGet(url: string, maxBytes: number): Promise<Uint8Array> {
  const response = await fetch(url, { method: "GET", redirect: "error" });
  // (d) non-2xx → fail loud (never treat an error body as an empty payload).
  if (!response.ok) {
    throw new Error(`challenge payload download failed with HTTP status ${response.status}`);
  }
  // (a) reject before reading the body when the server declares an oversized Content-Length.
  const declaredLength = Number(response.headers.get("content-length"));
  if (Number.isFinite(declaredLength) && declaredLength > maxBytes) {
    throw new Error(
      `challenge payload Content-Length ${declaredLength} exceeds the ${maxBytes}-byte cap`,
    );
  }
  return new Uint8Array(await response.arrayBuffer());
}

/** Resolved size/count caps for one fetch, with overrides applied ((a)/(b) shared by both readers). */
interface PayloadLimits {
  readonly maxPayloadBytes: number;
  readonly maxDecompressedBytes: number;
  readonly maxEntryCount: number;
  readonly maxEntryBytes: number;
}

function resolvePayloadLimits(deps: FetchChallengePayloadDeps): PayloadLimits {
  return {
    maxPayloadBytes: deps.maxPayloadBytes ?? MAX_PAYLOAD_BYTES,
    maxDecompressedBytes: deps.maxDecompressedBytes ?? MAX_DECOMPRESSED_BYTES,
    maxEntryCount: deps.maxEntryCount ?? MAX_ENTRY_COUNT,
    maxEntryBytes: deps.maxEntryBytes ?? MAX_ENTRY_BYTES,
  };
}

/**
 * (a) Download the payload and re-check the ACTUAL byte length against `maxPayloadBytes` — bounds
 * an injected fetcher too, and covers a server that under-declared (or omitted) Content-Length.
 * Shared by {@link fetchChallengePayloadArtifacts} and {@link fetchChallengePayloadDirectory}.
 */
async function downloadBoundedPayload(
  url: string,
  deps: FetchChallengePayloadDeps,
  limits: PayloadLimits,
): Promise<Uint8Array> {
  const httpGet = deps.httpGet ?? ((u: string) => defaultHttpGet(u, limits.maxPayloadBytes));
  const bytes = await httpGet(url);
  if (bytes.byteLength > limits.maxPayloadBytes) {
    throw new Error(
      `challenge payload is ${bytes.byteLength} bytes, exceeding the ${limits.maxPayloadBytes}-byte cap`,
    );
  }
  return bytes;
}

/**
 * (b) Backstops on an already-filtered, small inflated entry set (the `unzipSync` `filter` is the
 * PRIMARY decompress bound in both callers — it inflates only target entries within
 * `maxEntryBytes` each, so a zip-bomb hidden in a non-target or over-cap entry never inflates at
 * all): entry count, then a running decompressed-size sum. Shared by both readers.
 */
function enforceEntryBackstops(
  entries: Readonly<Record<string, Uint8Array>>,
  entryNames: readonly string[],
  limits: Pick<PayloadLimits, "maxEntryCount" | "maxDecompressedBytes">,
  buildCountExceededMessage: (count: number, cap: number) => string,
): void {
  if (entryNames.length > limits.maxEntryCount) {
    throw new Error(buildCountExceededMessage(entryNames.length, limits.maxEntryCount));
  }
  let decompressedTotal = 0;
  for (const name of entryNames) {
    decompressedTotal += entries[name].byteLength;
    if (decompressedTotal > limits.maxDecompressedBytes) {
      throw new Error(
        `challenge payload decompressed size exceeds the ${limits.maxDecompressedBytes}-byte cap`,
      );
    }
  }
}

/**
 * Fetch + unzip a private problem's `payload.zip` from its presigned URL and return the two files
 * the deploy needs. The template entry is the one whose key is exactly `template.yaml` or ends in
 * `/template.yaml`; its sibling `metadata.json` (same directory) is the metadata. Missing template
 * or missing sibling metadata throws (fail loud — never a silent empty artifact).
 */
export async function fetchChallengePayloadArtifacts(
  url: string,
  deps: FetchChallengePayloadDeps = {},
): Promise<ChallengePayloadArtifacts> {
  const limits = resolvePayloadLimits(deps);
  const bytes = await downloadBoundedPayload(url, deps, limits);

  // (b) PRIMARY decompress bound — see enforceEntryBackstops docblock.
  const entries = unzipSync(bytes, {
    filter: (file) => isTargetEntry(file.name) && file.originalSize <= limits.maxEntryBytes,
  });
  const entryNames = Object.keys(entries);
  enforceEntryBackstops(
    entries,
    entryNames,
    limits,
    (count, cap) => `challenge payload has ${count} entries, exceeding the ${cap} cap`,
  );

  const templateKey = entryNames.find(
    (key) => key === TEMPLATE_ENTRY || key.endsWith(`/${TEMPLATE_ENTRY}`),
  );
  if (!templateKey) {
    throw new Error(`challenge payload does not contain a ${TEMPLATE_ENTRY} entry`);
  }
  // Sibling metadata.json lives in the same directory as template.yaml.
  const dir = templateKey.slice(0, templateKey.length - TEMPLATE_ENTRY.length);
  const metadataKey = `${dir}${METADATA_ENTRY}`;
  const metadataEntry = entries[metadataKey];
  if (!metadataEntry) {
    throw new Error(`challenge payload is missing ${metadataKey} beside ${templateKey}`);
  }

  // (c) Decode only the two named entries in memory — nothing is written to disk.
  const decoder = new TextDecoder();
  return {
    templateBody: decoder.decode(entries[templateKey]),
    metadataText: decoder.decode(metadataEntry),
  };
}

/** One file recovered from underneath a payload directory entry, path-relative to that entry. */
export interface ChallengePayloadDirectoryFile {
  readonly relativePath: string;
  readonly bytes: Uint8Array;
}

/**
 * True when `name` (a full in-zip path) contains `entryDir` as a whole path-segment prefix
 * anywhere in its ancestry — i.e. a file living inside `.../{entryDir}/...`. A leading-segment
 * match (`entryDir` at the very start) or a `/`-preceded match (nested under an unknown organizer
 * root folder, same "any depth" allowance {@link isTargetEntry} makes) both count; a sibling like
 * `targets/gcp-old/main.tf` never matches `targets/gcp` because the character after the shared
 * prefix is `-`, not `/`.
 */
function isUnderEntryDir(name: string, entryDir: string): boolean {
  const marker = `${entryDir}/`;
  const idx = name.indexOf(marker);
  if (idx === -1) return false;
  return idx === 0 || name[idx - 1] === "/";
}

/** Strip the matched `.../{entryDir}/` prefix, leaving the path relative to that directory. */
function relativeToEntryDir(name: string, entryDir: string): string {
  const marker = `${entryDir}/`;
  const idx = name.indexOf(marker);
  return name.slice(idx + marker.length);
}

/**
 * Fetch + unzip a private problem's payload and return every file living under a declared
 * directory entry (a Terraform / Infrastructure Manager root module, unlike the two fixed
 * filenames {@link fetchChallengePayloadArtifacts} reads). `entryDir` is the problem-relative
 * directory path (e.g. `targets/gcp`, matching `runtime.entry` / a composite target's `entry`);
 * it must not be empty, absolute, or contain a `..` segment (defense-in-depth — the caller
 * validates the same, but this module never trusts a single layer). Returns files sorted by
 * `relativePath` for a deterministic caller-side zip. Missing directory (zero matching files)
 * throws (fail loud — never a silently empty blueprint).
 */
export async function fetchChallengePayloadDirectory(
  url: string,
  entryDir: string,
  deps: FetchChallengePayloadDeps = {},
): Promise<readonly ChallengePayloadDirectoryFile[]> {
  if (
    entryDir.length === 0 ||
    entryDir.startsWith("/") ||
    entryDir.split("/").includes("..") ||
    entryDir.includes("\\")
  ) {
    throw new Error(`challenge payload directory entry '${entryDir}' is not a valid relative path`);
  }
  const limits = resolvePayloadLimits(deps);
  const bytes = await downloadBoundedPayload(url, deps, limits);

  // (b) PRIMARY decompress bound — see enforceEntryBackstops docblock. Matched against an
  // arbitrary directory instead of two fixed filenames; directory marker entries (`name` ending
  // in `/`) never carry file content and are skipped.
  const entries = unzipSync(bytes, {
    filter: (file) =>
      !file.name.endsWith("/") &&
      isUnderEntryDir(file.name, entryDir) &&
      file.originalSize <= limits.maxEntryBytes,
  });
  const entryNames = Object.keys(entries);
  if (entryNames.length === 0) {
    throw new Error(`challenge payload does not contain any file under '${entryDir}/'`);
  }
  enforceEntryBackstops(
    entries,
    entryNames,
    limits,
    (count, cap) =>
      `challenge payload has ${count} entries under '${entryDir}/', exceeding the ${cap} cap`,
  );

  return entryNames
    .map((name) => ({ relativePath: relativeToEntryDir(name, entryDir), bytes: entries[name] }))
    .sort((a, b) => a.relativePath.localeCompare(b.relativePath));
}

/** Matches `entryName` at the zip root or nested under any directory depth. */
function matchesNamedEntry(name: string, entryName: string): boolean {
  return name === entryName || name.endsWith(`/${entryName}`);
}

/**
 * [Issue #2743] Fetch + unzip a private problem's payload and return the text of exactly ONE
 * author-chosen named entry — for a composite/non-AWS runtime target whose `entry` is a single
 * filename (e.g. `targets/azure.bicep` / `targets/azure.json`), unlike the two FIXED filenames
 * {@link fetchChallengePayloadArtifacts} reads or the whole DIRECTORY
 * {@link fetchChallengePayloadDirectory} reads. Shares the same `resolvePayloadLimits` /
 * `downloadBoundedPayload` / `enforceEntryBackstops` primitives as both siblings. Missing entry
 * throws (fail loud — never a silent empty artifact).
 */
export async function fetchChallengePayloadEntry(
  url: string,
  entryName: string,
  deps: FetchChallengePayloadDeps = {},
): Promise<string> {
  const limits = resolvePayloadLimits(deps);
  const bytes = await downloadBoundedPayload(url, deps, limits);

  // (b) PRIMARY decompress bound — see enforceEntryBackstops docblock.
  const entries = unzipSync(bytes, {
    filter: (file) =>
      matchesNamedEntry(file.name, entryName) && file.originalSize <= limits.maxEntryBytes,
  });
  const entryNames = Object.keys(entries);
  enforceEntryBackstops(
    entries,
    entryNames,
    limits,
    (count, cap) =>
      `challenge payload has ${count} entries matching '${entryName}', exceeding the ${cap} cap`,
  );
  // Fail loud on an ambiguous match — independent of maxEntryCount: a payload containing BOTH
  // `azure.json` and `targets/azure.json` would otherwise silently resolve `entryNames[0]`
  // (nondeterministic which entry, since Object.keys iteration order over the unzip result is not
  // a contract this module makes). Two-or-more matches is always a caller/payload error, never a
  // "pick one" situation.
  if (entryNames.length > 1) {
    throw new Error(
      `challenge payload has ${entryNames.length} entries matching '${entryName}' ` +
        `(${[...entryNames].sort().join(", ")}); the entry name must be unambiguous`,
    );
  }
  const matchedKey = entryNames[0];
  if (!matchedKey) {
    throw new Error(`challenge payload does not contain a '${entryName}' entry`);
  }
  return new TextDecoder().decode(entries[matchedKey]);
}
