import type { SimulatedCloudProblem } from "./simulator";
import type { SimulatorLauncherRecord } from "./simulator-launcher";

export interface SimulatorNativeRoute {
  readonly upstreamBaseUrl: string;
  readonly worldId: string;
  readonly deploymentId: string;
  readonly targetId: string;
}

export interface NativeTarget {
  readonly targetId: string;
  readonly provider: string;
  readonly engine: string;
}

interface NativeEnvironmentDeployment {
  readonly problemId: string;
  readonly worldId: string;
  readonly deploymentId: string;
  readonly launchToken: string;
}

interface NativeProfile {
  readonly problem: SimulatedCloudProblem;
  readonly deployment: NativeEnvironmentDeployment;
  readonly target: NativeTarget;
}

export function nativeTargets(problem: SimulatedCloudProblem): readonly NativeTarget[] {
  if (!("kind" in problem.runtime)) {
    return [
      {
        targetId: "default",
        provider: problem.runtime.provider,
        engine: problem.runtime.engine,
      },
    ];
  }
  return problem.runtime.targets.map((target) => ({
    targetId: target.id,
    provider: target.provider,
    engine: target.engine,
  }));
}

function shellLiteral(value: string): string {
  const escapedQuote = `'"'"'`;
  return `'${value.replaceAll("'", escapedQuote)}'`;
}

function profileValues(
  profile: NativeProfile,
  launcher: SimulatorLauncherRecord,
  proxyBaseUrl: string,
): Readonly<Record<string, string>> {
  const { problem, deployment, target } = profile;
  const nativeEndpoint = `${proxyBaseUrl.replace(/\/$/, "")}/local/simulator-native/${encodeURIComponent(problem.problemId)}/${encodeURIComponent(target.targetId)}`;
  const separator = launcher.nativeCredentials.sakuraCredential.indexOf(":");
  return {
    TENKACLOUD_SIMULATOR_PROFILE: `${problem.problemId}:${target.targetId}`,
    TENKACLOUD_SIMULATOR_ENDPOINT: launcher.baseUrl,
    TENKACLOUD_SIMULATOR_NATIVE_ENDPOINT: nativeEndpoint,
    TENKACLOUD_SIMULATOR_TOKEN: deployment.launchToken,
    TENKACLOUD_SIMULATOR_WORLD_ID: deployment.worldId,
    TENKACLOUD_SIMULATOR_DEPLOYMENT_ID: deployment.deploymentId,
    TENKACLOUD_SIMULATOR_TARGET_ID: target.targetId,
    TENKACLOUD_SIMULATOR_PROVIDER: target.provider,
    TENKACLOUD_SIMULATOR_ENGINE: target.engine,
    TENKACLOUD_SIMULATOR_AZURE_CREDENTIAL: launcher.nativeCredentials.azureCredential,
    TENKACLOUD_SIMULATOR_AZURE_ENDPOINT: nativeEndpoint,
    TENKACLOUD_SIMULATOR_GCP_CREDENTIAL: launcher.nativeCredentials.gcpCredential,
    TENKACLOUD_SIMULATOR_GCP_ENDPOINT: nativeEndpoint,
    TENKACLOUD_SIMULATOR_SAKURA_CREDENTIAL: launcher.nativeCredentials.sakuraCredential,
    TENKACLOUD_SIMULATOR_SAKURA_ENDPOINT: nativeEndpoint,
    AWS_ACCESS_KEY_ID: launcher.nativeCredentials.awsAccessKeyId,
    AWS_SECRET_ACCESS_KEY: launcher.nativeCredentials.awsSecretAccessKey,
    AWS_REGION: "us-east-1",
    AWS_ENDPOINT_URL: nativeEndpoint,
    SAKURACLOUD_ACCESS_TOKEN: launcher.nativeCredentials.sakuraCredential.slice(0, separator),
    SAKURACLOUD_ACCESS_TOKEN_SECRET: launcher.nativeCredentials.sakuraCredential.slice(
      separator + 1,
    ),
  };
}

/** Build a source-able, multi-profile shell artifact without requiring custom provider headers. */
export function simulatorNativeEnvironment(
  launcher: SimulatorLauncherRecord,
  deployments: ReadonlyMap<string, NativeEnvironmentDeployment>,
  problems: ReadonlyMap<string, SimulatedCloudProblem>,
  proxyBaseUrl: string,
): string {
  const profiles: NativeProfile[] = [];
  for (const [problemId, deployment] of deployments) {
    const problem = problems.get(problemId);
    if (!problem) continue;
    for (const target of nativeTargets(problem)) profiles.push({ problem, deployment, target });
  }
  profiles.sort((left, right) =>
    `${left.problem.problemId}:${left.target.targetId}`.localeCompare(
      `${right.problem.problemId}:${right.target.targetId}`,
    ),
  );
  if (profiles.length === 0) return "";
  const names = profiles.map(({ problem, target }) => `${problem.problemId}:${target.targetId}`);
  const lines = [
    "# Generated by TenkaCloud local play. File mode: 0600.",
    `export TENKACLOUD_SIMULATOR_PROFILES=${shellLiteral(names.join(" "))}`,
    `TENKACLOUD_SIMULATOR_DEFAULT_PROFILE=${shellLiteral(names[0] ?? "")}`,
    "tenkacloud_simulator_use() {",
    '  case "$1" in',
  ];
  for (const profile of profiles) {
    const name = `${profile.problem.problemId}:${profile.target.targetId}`;
    lines.push(`    ${shellLiteral(name)})`);
    for (const [key, value] of Object.entries(profileValues(profile, launcher, proxyBaseUrl))) {
      lines.push(`      export ${key}=${shellLiteral(value)}`);
    }
    lines.push("      ;;");
  }
  lines.push(
    "    *)",
    '      printf \'Unknown Simulator profile: %s\\nAvailable: %s\\n\' "$1" "$TENKACLOUD_SIMULATOR_PROFILES" >&2',
    "      return 1",
    "      ;;",
    "  esac",
    "}",
    `tenkacloud_simulator_use "\${TENKACLOUD_SIMULATOR_PROFILE:-$TENKACLOUD_SIMULATOR_DEFAULT_PROFILE}"`,
    "",
  );
  return lines.join("\n");
}
