import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";

const root = join(import.meta.dir, "../..");
const read = (path: string) => readFileSync(join(root, path), "utf8");

type ContactFormModule = {
  parseConfig: (raw: unknown) => { formResponseUrl: string; fields: Record<string, unknown> };
  validate: (
    config: { fields: Record<string, { required?: boolean }> },
    values: Record<string, string>,
  ) => Array<{ key: string; reason: string }>;
  buildPayload: (
    config: { fields: Record<string, { entryId: string }> },
    values: Record<string, string>,
  ) => Array<[string, string]>;
  submit: (
    config: { formResponseUrl: string; fields: Record<string, { entryId: string }> },
    values: Record<string, string>,
    runtime: { fetch: typeof fetch },
  ) => Promise<unknown>;
};

const contactForm = createRequire(import.meta.url)(
  join(root, "landing/contact-form.js"),
) as ContactFormModule;

const validConfig = {
  formResponseUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfake0Example/formResponse",
  fields: {
    name: { entryId: "entry.100", title: "お名前", required: true },
    organization: { entryId: "entry.200", title: "会社・組織名", required: false },
    email: { entryId: "entry.300", title: "メールアドレス", required: true },
    message: { entryId: "entry.400", title: "お問い合わせ内容", required: true },
  },
};

describe("landing contact form config", () => {
  it("should accept a config generated by the form sync workflow", () => {
    const parsed = contactForm.parseConfig(structuredClone(validConfig));
    expect(parsed.formResponseUrl).toBe(validConfig.formResponseUrl);
    expect(Object.keys(parsed.fields)).toEqual(["name", "organization", "email", "message"]);
  });

  it("should reject a response URL that is not a Google Form endpoint", () => {
    const config = { ...structuredClone(validConfig), formResponseUrl: "https://example.com/post" };
    expect(() => contactForm.parseConfig(config)).toThrow(/unexpected formResponseUrl/);
  });

  it("should reject a viewform URL that was not rewritten to formResponse", () => {
    const config = {
      ...structuredClone(validConfig),
      formResponseUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfake0Example/viewform",
    };
    expect(() => contactForm.parseConfig(config)).toThrow(/unexpected formResponseUrl/);
  });

  it("should reject a config whose entry id is missing or malformed", () => {
    const missing = structuredClone(validConfig);
    // @ts-expect-error 破損した設定を意図的に作る
    missing.fields.email.entryId = undefined;
    expect(() => contactForm.parseConfig(missing)).toThrow(/invalid entry id for email/);

    const malformed = structuredClone(validConfig);
    malformed.fields.email.entryId = "entry.abc";
    expect(() => contactForm.parseConfig(malformed)).toThrow(/invalid entry id for email/);
  });

  it("should reject an empty or non-object config", () => {
    expect(() => contactForm.parseConfig(null)).toThrow(/not an object/);
    expect(() => contactForm.parseConfig({ ...validConfig, fields: {} })).toThrow(/no fields/);
    expect(() => contactForm.parseConfig({ formResponseUrl: validConfig.formResponseUrl })).toThrow(
      /no fields/,
    );
  });
});

describe("landing contact form validation", () => {
  it("should report every empty required field", () => {
    const problems = contactForm.validate(validConfig, {
      name: "",
      organization: "BULL",
      email: "  ",
      message: "相談したい",
    });
    expect(problems).toEqual([
      { key: "name", reason: "required" },
      { key: "email", reason: "required" },
    ]);
  });

  it("should reject a malformed email before the no-cors POST hides the failure", () => {
    const problems = contactForm.validate(validConfig, {
      name: "富田",
      email: "not-an-email",
      message: "相談したい",
    });
    expect(problems).toEqual([{ key: "email", reason: "email" }]);
  });

  it("should accept a complete submission", () => {
    expect(
      contactForm.validate(validConfig, {
        name: "富田",
        organization: "",
        email: "user@example.com",
        message: "相談したい",
      }),
    ).toEqual([]);
  });
});

describe("landing contact form payload", () => {
  it("should map every value onto the entry id from the synced config", () => {
    expect(
      contactForm.buildPayload(validConfig, {
        name: "富田",
        email: "user@example.com",
        message: "相談したい",
      }),
    ).toEqual([
      ["entry.100", "富田"],
      ["entry.300", "user@example.com"],
      ["entry.400", "相談したい"],
    ]);
  });

  it("should drop blank optional values instead of sending empty answers", () => {
    expect(contactForm.buildPayload(validConfig, { name: "富田", organization: "   " })).toEqual([
      ["entry.100", "富田"],
    ]);
  });

  it("should fail loudly when a field has no entry id in the config", () => {
    expect(() => contactForm.buildPayload(validConfig, { phone: "000" })).toThrow(
      /no entry id for: phone/,
    );
  });
});

describe("landing contact form submission", () => {
  it("should POST the entry-keyed form data to the Google Form endpoint", async () => {
    const calls: Array<{ url: string; init: RequestInit }> = [];
    const recordingFetch = (async (url: string, init: RequestInit) => {
      calls.push({ url, init });
      return new Response(null, { status: 200 });
    }) as unknown as typeof fetch;

    await contactForm.submit(
      validConfig,
      { name: "富田", email: "user@example.com", message: "相談したい" },
      { fetch: recordingFetch },
    );

    expect(calls).toHaveLength(1);
    expect(calls[0].url).toBe(validConfig.formResponseUrl);
    expect(calls[0].init.method).toBe("POST");
    // no-cors でしか送れない (= CORS プリフライトを避ける) ため、 応答は読めない。
    expect(calls[0].init.mode).toBe("no-cors");
    const body = calls[0].init.body as URLSearchParams;
    expect(body.get("entry.100")).toBe("富田");
    expect(body.get("entry.300")).toBe("user@example.com");
    expect(body.get("entry.400")).toBe("相談したい");
  });

  it("should not swallow a network failure", async () => {
    const failingFetch = (async () => {
      throw new Error("network down");
    }) as unknown as typeof fetch;

    await expect(
      contactForm.submit(
        validConfig,
        { name: "富田", email: "user@example.com", message: "相談したい" },
        { fetch: failingFetch },
      ),
    ).rejects.toThrow("network down");
  });
});

describe("landing contact form wiring", () => {
  const index = read("landing/index.html");
  const app = read("landing/app.js");

  it("should keep the hosted Google Form link as the no-JavaScript fallback", () => {
    expect(index).toContain('href="https://forms.gle/djVprYmq3hFgJA7P9"');
  });

  it("should ship a field for every key the synced config carries", () => {
    for (const key of ["name", "organization", "email", "topic", "message"]) {
      expect(index).toContain(`data-form-field="${key}"`);
    }
  });

  it("should load the entry map at runtime rather than hardcoding entry ids", () => {
    expect(app).toContain("./contact-form-config.json");
    expect(index).not.toMatch(/entry\.\d+/);
    expect(app).not.toMatch(/entry\.\d+/);
  });

  it("should reveal the inline form only after the config validates", () => {
    expect(app).toContain("TenkaContactForm.parseConfig");
    expect(app).toContain("contact-form-ready");
  });
});
