import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";

const root = join(import.meta.dir, "../..");
const read = (path: string) => readFileSync(join(root, path), "utf8");

type Field = { entryId: string; required?: boolean; kind: string; choices?: string[] | null };

type ContactFormModule = {
  parseConfig: (raw: unknown) => { formResponseUrl: string; fields: Record<string, unknown> };
  validate: (
    config: { fields: Record<string, Field & { validation?: string | null }> },
    values: Record<string, string>,
  ) => Array<{ key: string; reason: string }>;
  buildPayload: (
    config: { fields: Record<string, Field> },
    values: Record<string, string>,
  ) => Array<[string, string]>;
  submit: (
    config: { formResponseUrl: string; fields: Record<string, Field> },
    values: Record<string, string>,
    runtime: { fetch: typeof fetch },
  ) => Promise<unknown>;
};

const contactForm = createRequire(import.meta.url)(
  join(root, "landing/contact-form.js"),
) as ContactFormModule;

const field = (over: Partial<Field> & { entryId: string }) => ({
  title: "t",
  required: false,
  kind: "text",
  validation: null,
  choices: null,
  ...over,
});

const validConfig = {
  formResponseUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfake0Example/formResponse",
  fields: {
    name: field({ entryId: "entry.100", required: true }),
    organization: field({ entryId: "entry.200" }),
    email: field({ entryId: "entry.300", required: true, validation: "email" }),
    topic: field({
      entryId: "entry.400",
      required: true,
      kind: "choice",
      choices: ["A", "B"],
    }),
    message: field({ entryId: "entry.500", required: true, kind: "paragraph" }),
  },
};

const clone = () => structuredClone(validConfig);

describe("landing contact form config", () => {
  it("should accept a config generated by the form sync workflow", () => {
    const parsed = contactForm.parseConfig(clone());
    expect(parsed.formResponseUrl).toBe(validConfig.formResponseUrl);
    expect(Object.keys(parsed.fields)).toEqual([
      "name",
      "organization",
      "email",
      "topic",
      "message",
    ]);
  });

  it("should reject a response URL that is not a Google Form endpoint", () => {
    expect(() =>
      contactForm.parseConfig({ ...clone(), formResponseUrl: "https://example.com/post" }),
    ).toThrow(/unexpected formResponseUrl/);
  });

  it("should reject a viewform URL that was not rewritten to formResponse", () => {
    expect(() =>
      contactForm.parseConfig({
        ...clone(),
        formResponseUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfake0Example/viewform",
      }),
    ).toThrow(/unexpected formResponseUrl/);
  });

  it("should reject a config whose entry id is missing or malformed", () => {
    const missing = clone();
    // @ts-expect-error 破損した設定を意図的に作る
    missing.fields.email.entryId = undefined;
    expect(() => contactForm.parseConfig(missing)).toThrow(/invalid entry id for email/);

    const malformed = clone();
    malformed.fields.email.entryId = "entry.abc";
    expect(() => contactForm.parseConfig(malformed)).toThrow(/invalid entry id for email/);
  });

  it("should reject a field whose control kind is unknown", () => {
    const config = clone();
    config.fields.name.kind = "slider";
    expect(() => contactForm.parseConfig(config)).toThrow(/unknown kind for name/);
  });

  it("should reject a choice field that carries no choices", () => {
    const config = clone();
    config.fields.topic.choices = [];
    expect(() => contactForm.parseConfig(config)).toThrow(/no choices for topic/);
  });

  it("should reject an empty or non-object config", () => {
    expect(() => contactForm.parseConfig(null)).toThrow(/not an object/);
    expect(() => contactForm.parseConfig({ ...validConfig, fields: {} })).toThrow(/no fields/);
    expect(() => contactForm.parseConfig({ formResponseUrl: validConfig.formResponseUrl })).toThrow(
      /no fields/,
    );
  });
});

describe("landing contact form validation", () => {
  it("should report every empty required field", () => {
    expect(
      contactForm.validate(validConfig, {
        name: "",
        organization: "BULL",
        email: "  ",
        topic: "A",
        message: "相談したい",
      }),
    ).toEqual([
      { key: "name", reason: "required" },
      { key: "email", reason: "required" },
    ]);
  });

  it("should reject a malformed email before the no-cors POST hides the failure", () => {
    expect(
      contactForm.validate(validConfig, {
        name: "富田",
        email: "not-an-email",
        topic: "A",
        message: "相談したい",
      }),
    ).toEqual([{ key: "email", reason: "email" }]);
  });

  it("should drive email checking from the config, not from the field name", () => {
    // key を変えても検証が付いてくることを確かめる。 key 名で分岐していると
    // 「key をリネームしたら検証が黙って外れる」 という壊れ方をする。
    const renamed = {
      formResponseUrl: validConfig.formResponseUrl,
      fields: { reply_to: field({ entryId: "entry.900", required: true, validation: "email" }) },
    };
    expect(contactForm.validate(renamed, { reply_to: "nope" })).toEqual([
      { key: "reply_to", reason: "email" },
    ]);
  });

  it("should accept a complete submission", () => {
    expect(
      contactForm.validate(validConfig, {
        name: "富田",
        organization: "",
        email: "user@example.com",
        topic: "A",
        message: "相談したい",
      }),
    ).toEqual([]);
  });
});

describe("landing contact form payload", () => {
  const complete = {
    name: "富田",
    organization: "",
    email: "user@example.com",
    topic: "A",
    message: "相談したい",
  };

  it("should map every value onto the entry id from the synced config", () => {
    expect(contactForm.buildPayload(validConfig, complete)).toEqual([
      ["entry.100", "富田"],
      ["entry.300", "user@example.com"],
      ["entry.400", "A"],
      ["entry.500", "相談したい"],
    ]);
  });

  it("should drop blank optional values instead of sending empty answers", () => {
    expect(contactForm.buildPayload(validConfig, complete).map((pair) => pair[0])).not.toContain(
      "entry.200",
    );
  });

  it("should fail loudly when a field has no entry id in the config", () => {
    expect(() => contactForm.buildPayload(validConfig, { ...complete, phone: "000" })).toThrow(
      /no entry id for: phone/,
    );
  });

  it("should refuse to build a payload that omits a required answer", () => {
    // 検証を飛ばして呼ばれても、 Google に黙って捨てられる送信は作らない。
    expect(() => contactForm.buildPayload(validConfig, { ...complete, message: "  " })).toThrow(
      /missing required values for: message/,
    );
  });
});

describe("landing contact form submission", () => {
  const complete = {
    name: "富田",
    organization: "",
    email: "user@example.com",
    topic: "A",
    message: "相談したい",
  };

  it("should POST the entry-keyed form data to the Google Form endpoint", async () => {
    const calls: Array<{ url: string; init: RequestInit }> = [];
    const recordingFetch = (async (url: string, init: RequestInit) => {
      calls.push({ url, init });
      return new Response(null, { status: 200 });
    }) as unknown as typeof fetch;

    await contactForm.submit(validConfig, complete, { fetch: recordingFetch });

    expect(calls).toHaveLength(1);
    expect(calls[0].url).toBe(validConfig.formResponseUrl);
    expect(calls[0].init.method).toBe("POST");
    // no-cors でしか送れない (= CORS プリフライトを避ける) ため、 応答は読めない。
    expect(calls[0].init.mode).toBe("no-cors");
    const body = calls[0].init.body as URLSearchParams;
    expect(body.get("entry.100")).toBe("富田");
    expect(body.get("entry.300")).toBe("user@example.com");
    expect(body.get("entry.500")).toBe("相談したい");
  });

  it("should not swallow a network failure", async () => {
    const failingFetch = (async () => {
      throw new Error("network down");
    }) as unknown as typeof fetch;

    await expect(
      contactForm.submit(validConfig, complete, { fetch: failingFetch }),
    ).rejects.toThrow("network down");
  });
});

describe("landing contact form wiring", () => {
  const index = read("landing/index.html");
  const app = read("landing/app.js");
  const sync = read("form/sync.gs");

  it("should keep the hosted Google Form link as the no-JavaScript fallback", () => {
    expect(index).toContain('href="https://forms.gle/djVprYmq3hFgJA7P9"');
  });

  it("should ship a field for every key the synced config carries", () => {
    for (const key of ["name", "organization", "email", "topic", "message"]) {
      expect(index).toContain(`data-form-field="${key}"`);
    }
  });

  it("should load the entry map at runtime rather than hardcoding entry ids", () => {
    expect(app).toContain("./contact-form-config.json");
    expect(index).not.toMatch(/entry\.\d+/);
    expect(app).not.toMatch(/entry\.\d+/);
  });

  it("should reveal the inline form only after the config validates", () => {
    expect(app).toContain("TenkaContactForm.parseConfig");
    expect(app).toContain("contact-form-ready");
  });

  /**
   * 選択肢は Google 側の値そのものを送る必要があるので、 sync.gs の定義と
   * HTML の option value は一字一句一致していなければならない。 実行時にも
   * assertMatchesConfig が突き合わせるが、 それは同期が済んだ後にしか働かない。
   * ここで先に落としておく。
   */
  it("should keep the topic options identical to the form definition", () => {
    const block = sync.match(/key: "topic"[\s\S]*?choices: \[([\s\S]*?)\]/);
    expect(block).not.toBeNull();
    const defined = [...String(block?.[1]).matchAll(/"([^"]+)"/g)].map((match) => match[1]);
    expect(defined.length).toBeGreaterThan(0);

    const select = index.match(/<select id="contact-topic"[\s\S]*?<\/select>/);
    const rendered = [...String(select?.[0]).matchAll(/<option value="([^"]*)"/g)]
      .map((match) => match[1])
      .filter((value) => value !== "");
    expect(rendered).toEqual(defined);
  });

  it("should let the required select start empty so it can actually fail validation", () => {
    const select = String(index.match(/<select id="contact-topic"[\s\S]*?<\/select>/)?.[0]);
    expect(select).toContain('<option value=""');
  });

  it("should mark required controls for assistive technology", () => {
    for (const id of ["contact-name", "contact-email", "contact-topic", "contact-message"]) {
      const control = String(index.match(new RegExp(`id="${id}"[^>]*`))?.[0]);
      expect(control).toContain('aria-required="true"');
      expect(control).toContain(`aria-describedby="${id}-error"`);
    }
  });

  /**
   * 必須の食い違いは選択肢のズレと同じ壊れ方をする。 フォーム側だけ必須になると
   * LP は空欄のまま送れてしまい、 Google に弾かれた事実は no-cors に隠れる。
   * 実行時の assertField も見るが、 同期が済むまでは働かないのでここで落とす。
   */
  it("should keep required flags identical to the form definition", () => {
    const defined = [...sync.matchAll(/key: "(\w+)",[\s\S]{0,200}?required: (true|false)/g)].map(
      (match) => [match[1], match[2] === "true"] as const,
    );
    expect(defined.length).toBe(5);
    for (const [key, required] of defined) {
      const control = String(index.match(new RegExp(`data-form-field="${key}"[^>]*`))?.[0]);
      expect([key, / required\b/.test(control)]).toEqual([key, required]);
    }
  });

  /**
   * まとめ表示と項目ごとの文言は別の文にする。 同じ文を 2 箇所へ出すと、
   * 1 項目だけ直したときにどちらを指しているのか判別できない。
   */
  it("should show a summary message distinct from the per-field ones", () => {
    expect(app).toContain('setStatus("form.hasErrors", "error")');
    // ja / en の両方に訳が要る。 片方だけだと切り替えた瞬間に空文字になる。
    expect([...app.matchAll(/"form\.hasErrors":/g)]).toHaveLength(2);
    expect(app).not.toContain('setStatus("form.required"');
    expect(app).not.toContain('setStatus("form.invalidEmail"');
  });

  it("should retract the summary message once every problem is corrected", () => {
    expect(app).toContain("function syncErrorBanner()");
    expect(app).toContain("syncErrorBanner();");
  });
});
