import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";

const root = join(import.meta.dir, "../..");
const read = (path: string) => readFileSync(join(root, path), "utf8");

interface Field {
  entryId: string;
  required?: boolean;
  kind: string;
  choices?: string[] | null;
}

interface ContactFormModule {
  parseConfig: (raw: unknown) => { formResponseUrl: string; fields: Record<string, unknown> };
  validate: (
    config: { fields: Record<string, Field & { validation?: string | null }> },
    values: Record<string, string>,
  ) => { key: string; reason: string }[];
  buildPayload: (
    config: { fields: Record<string, Field> },
    values: Record<string, string>,
  ) => [string, string][];
  submit: (
    config: { formResponseUrl: string; fields: Record<string, Field> },
    values: Record<string, string>,
    runtime: { fetch: typeof fetch },
  ) => Promise<unknown>;
}

const contactForm = createRequire(import.meta.url)(
  join(root, "landing/contact-form.js"),
) as ContactFormModule;

const field = (over: Partial<Field> & { entryId: string }) => ({
  title: "t",
  required: false,
  kind: "text",
  validation: null,
  choices: null,
  ...over,
});

const validConfig = {
  formResponseUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfake0Example/formResponse",
  fields: {
    name: field({ entryId: "entry.100", required: true }),
    organization: field({ entryId: "entry.200" }),
    email: field({ entryId: "entry.300", required: true, validation: "email" }),
    topic: field({
      entryId: "entry.400",
      required: true,
      kind: "choice",
      choices: ["A", "B"],
    }),
    message: field({ entryId: "entry.500", required: true, kind: "paragraph" }),
  },
};

const clone = () => structuredClone(validConfig);

describe("landing contact form config", () => {
  it("should accept a config generated by the form sync workflow", () => {
    const parsed = contactForm.parseConfig(clone());
    expect(parsed.formResponseUrl).toBe(validConfig.formResponseUrl);
    expect(Object.keys(parsed.fields)).toEqual([
      "name",
      "organization",
      "email",
      "topic",
      "message",
    ]);
  });

  it("should reject a response URL that is not a Google Form endpoint", () => {
    expect(() =>
      contactForm.parseConfig({ ...clone(), formResponseUrl: "https://example.com/post" }),
    ).toThrow(/unexpected formResponseUrl/);
  });

  it("should reject a viewform URL that was not rewritten to formResponse", () => {
    expect(() =>
      contactForm.parseConfig({
        ...clone(),
        formResponseUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfake0Example/viewform",
      }),
    ).toThrow(/unexpected formResponseUrl/);
  });

  it("should reject a config whose entry id is missing or malformed", () => {
    const missing = clone();
    // @ts-expect-error 破損した設定を意図的に作る
    missing.fields.email.entryId = undefined;
    expect(() => contactForm.parseConfig(missing)).toThrow(/invalid entry id for email/);

    const malformed = clone();
    malformed.fields.email.entryId = "entry.abc";
    expect(() => contactForm.parseConfig(malformed)).toThrow(/invalid entry id for email/);
  });

  it("should reject a field whose control kind is unknown", () => {
    const config = clone();
    config.fields.name.kind = "slider";
    expect(() => contactForm.parseConfig(config)).toThrow(/unknown kind for name/);
  });

  it("should reject a choice field that carries no choices", () => {
    const config = clone();
    config.fields.topic.choices = [];
    expect(() => contactForm.parseConfig(config)).toThrow(/no choices for topic/);
  });

  it("should reject an empty or non-object config", () => {
    expect(() => contactForm.parseConfig(null)).toThrow(/not an object/);
    expect(() => contactForm.parseConfig({ ...validConfig, fields: {} })).toThrow(/no fields/);
    expect(() => contactForm.parseConfig({ formResponseUrl: validConfig.formResponseUrl })).toThrow(
      /no fields/,
    );
  });
});

describe("landing contact form validation", () => {
  it("should report every empty required field", () => {
    expect(
      contactForm.validate(validConfig, {
        name: "",
        organization: "BULL",
        email: "  ",
        topic: "A",
        message: "相談したい",
      }),
    ).toEqual([
      { key: "name", reason: "required" },
      { key: "email", reason: "required" },
    ]);
  });

  it("should reject a malformed email before the no-cors POST hides the failure", () => {
    expect(
      contactForm.validate(validConfig, {
        name: "富田",
        email: "not-an-email",
        topic: "A",
        message: "相談したい",
      }),
    ).toEqual([{ key: "email", reason: "email" }]);
  });

  it("should drive email checking from the config, not from the field name", () => {
    // key を変えても検証が付いてくることを確かめる。 key 名で分岐していると
    // 「key をリネームしたら検証が黙って外れる」 という壊れ方をする。
    const renamed = {
      formResponseUrl: validConfig.formResponseUrl,
      fields: { reply_to: field({ entryId: "entry.900", required: true, validation: "email" }) },
    };
    expect(contactForm.validate(renamed, { reply_to: "nope" })).toEqual([
      { key: "reply_to", reason: "email" },
    ]);
  });

  it("should accept a complete submission", () => {
    expect(
      contactForm.validate(validConfig, {
        name: "富田",
        organization: "",
        email: "user@example.com",
        topic: "A",
        message: "相談したい",
      }),
    ).toEqual([]);
  });
});

describe("landing contact form payload", () => {
  const complete = {
    name: "富田",
    organization: "",
    email: "user@example.com",
    topic: "A",
    message: "相談したい",
  };

  it("should map every value onto the entry id from the synced config", () => {
    expect(contactForm.buildPayload(validConfig, complete)).toEqual([
      ["entry.100", "富田"],
      ["entry.300", "user@example.com"],
      ["entry.400", "A"],
      ["entry.500", "相談したい"],
    ]);
  });

  it("should drop blank optional values instead of sending empty answers", () => {
    expect(contactForm.buildPayload(validConfig, complete).map((pair) => pair[0])).not.toContain(
      "entry.200",
    );
  });

  it("should fail loudly when a field has no entry id in the config", () => {
    expect(() => contactForm.buildPayload(validConfig, { ...complete, phone: "000" })).toThrow(
      /no entry id for: phone/,
    );
  });

  it("should refuse to build a payload that omits a required answer", () => {
    // 検証を飛ばして呼ばれても、 Google に黙って捨てられる送信は作らない。
    expect(() => contactForm.buildPayload(validConfig, { ...complete, message: "  " })).toThrow(
      /missing required values for: message/,
    );
  });
});

describe("landing contact form submission", () => {
  const complete = {
    name: "富田",
    organization: "",
    email: "user@example.com",
    topic: "A",
    message: "相談したい",
  };

  it("should POST the entry-keyed form data to the Google Form endpoint", async () => {
    const calls: { url: string; init: RequestInit }[] = [];
    const recordingFetch = (async (url: string, init: RequestInit) => {
      calls.push({ url, init });
      return new Response(null, { status: 200 });
    }) as unknown as typeof fetch;

    await contactForm.submit(validConfig, complete, { fetch: recordingFetch });

    expect(calls).toHaveLength(1);
    expect(calls[0].url).toBe(validConfig.formResponseUrl);
    expect(calls[0].init.method).toBe("POST");
    // no-cors でしか送れない (= CORS プリフライトを避ける) ため、 応答は読めない。
    expect(calls[0].init.mode).toBe("no-cors");
    const body = calls[0].init.body as URLSearchParams;
    expect(body.get("entry.100")).toBe("富田");
    expect(body.get("entry.300")).toBe("user@example.com");
    expect(body.get("entry.500")).toBe("相談したい");
  });

  it("should not swallow a network failure", async () => {
    const failingFetch = (async () => {
      throw new Error("network down");
    }) as unknown as typeof fetch;

    await expect(
      contactForm.submit(validConfig, complete, { fetch: failingFetch }),
    ).rejects.toThrow("network down");
  });
});

describe("landing contact form wiring", () => {
  const index = read("landing/index.html");
  const app = read("landing/app.js");
  const sync = read("form/sync.gs");

  it("should keep the hosted Google Form link as the no-JavaScript fallback", () => {
    expect(index).toContain('href="https://forms.gle/djVprYmq3hFgJA7P9"');
  });

  it("should ship a field for every key the synced config carries", () => {
    for (const key of ["name", "organization", "email", "topic", "message"]) {
      expect(index).toContain(`data-form-field="${key}"`);
    }
  });

  it("should load the entry map at runtime rather than hardcoding entry ids", () => {
    expect(app).toContain("./contact-form-config.json");
    expect(index).not.toMatch(/entry\.\d+/);
    expect(app).not.toMatch(/entry\.\d+/);
  });

  it("should reveal the inline form only after the config validates", () => {
    expect(app).toContain("TenkaContactForm.parseConfig");
    expect(app).toContain("contact-form-ready");
  });

  /**
   * 選択肢は Google 側の値そのものを送る必要があるので、 sync.gs の定義と
   * HTML の option value は一字一句一致していなければならない。 実行時にも
   * assertMatchesConfig が突き合わせるが、 それは同期が済んだ後にしか働かない。
   * ここで先に落としておく。
   */
  it("should keep the topic options identical to the form definition", () => {
    const block = sync.match(/key: "topic"[\s\S]*?choices: \[([\s\S]*?)\]/);
    expect(block).not.toBeNull();
    const defined = [...String(block?.[1]).matchAll(/"([^"]+)"/g)].map((match) => match[1]);
    expect(defined.length).toBeGreaterThan(0);

    const select = index.match(/<select id="contact-topic"[\s\S]*?<\/select>/);
    const rendered = [...String(select?.[0]).matchAll(/<option value="([^"]*)"/g)]
      .map((match) => match[1])
      .filter((value) => value !== "");
    expect(rendered).toEqual(defined);
  });

  it("should let the required select start empty so it can actually fail validation", () => {
    const select = String(index.match(/<select id="contact-topic"[\s\S]*?<\/select>/)?.[0]);
    expect(select).toContain('<option value=""');
  });

  it("should mark required controls for assistive technology", () => {
    for (const id of ["contact-name", "contact-email", "contact-topic", "contact-message"]) {
      const control = String(index.match(new RegExp(`id="${id}"[^>]*`))?.[0]);
      expect(control).toContain('aria-required="true"');
      expect(control).toContain(`aria-describedby="${id}-error"`);
    }
  });

  /**
   * 必須の食い違いは選択肢のズレと同じ壊れ方をする。 フォーム側だけ必須になると
   * LP は空欄のまま送れてしまい、 Google に弾かれた事実は no-cors に隠れる。
   * 実行時の assertField も見るが、 同期が済むまでは働かないのでここで落とす。
   */
  it("should keep required flags identical to the form definition", () => {
    const defined = [...sync.matchAll(/key: "(\w+)",[\s\S]{0,200}?required: (true|false)/g)].map(
      (match) => [match[1], match[2] === "true"] as const,
    );
    expect(defined.length).toBe(5);
    for (const [key, required] of defined) {
      const control = String(index.match(new RegExp(`data-form-field="${key}"[^>]*`))?.[0]);
      expect([key, / required\b/.test(control)]).toEqual([key, required]);
    }
  });

  /**
   * まとめ表示と項目ごとの文言は別の文にする。 同じ文を 2 箇所へ出すと、
   * 1 項目だけ直したときにどちらを指しているのか判別できない。
   */
  it("should translate the summary message into both languages", () => {
    // 片方だけだと、 言語を切り替えた瞬間に警告が空文字になる。
    expect([...app.matchAll(/"form\.hasErrors":/g)]).toHaveLength(2);
  });
});

/**
 * ここだけは本物の DOM で動かす。 landing/app.js はブラウザ専用の IIFE なので、
 * ソース文字列の一致で確かめても 「その関数が呼ばれたら実際どうなるか」 は何も
 * 保証できない。 送信の成否が no-cors で見えない以上、 送信前の入力検証こそが
 * 唯一の防波堤で、 それが本当に働くことは実物で確かめる必要がある。
 */
describe("landing contact form behaviour", () => {
  const CONFIG = {
    formResponseUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfake0Example/formResponse",
    fields: {
      name: field({ entryId: "entry.100", title: "お名前", required: true }),
      organization: field({ entryId: "entry.200", title: "会社・組織名" }),
      email: field({
        entryId: "entry.300",
        title: "メールアドレス",
        required: true,
        validation: "email",
      }),
      topic: field({
        entryId: "entry.400",
        title: "お問い合わせ種別",
        required: true,
        kind: "choice",
        choices: [
          "プラン・見積もりの相談",
          "企業内の研修・演習での利用",
          "カスタム問題の追加開発",
          "その他",
        ],
      }),
      message: field({
        entryId: "entry.500",
        title: "お問い合わせ内容",
        required: true,
        kind: "paragraph",
      }),
    },
  };

  /**
   * index.html を実 DOM に載せ、 contact-form.js と app.js をその window の中で
   * 評価する。 設定の取得だけを差し替え、 それ以外は本番と同じ経路を通す。
   */
  async function mount(config: unknown) {
    const { JSDOM } = (await import("jsdom")) as typeof import("jsdom");
    // 言語は URL で固定する。 既定は navigator.language 依存なので、 実行環境の
    // ロケールでテストの期待文言が変わってしまう。
    const dom = new JSDOM(read("landing/index.html"), {
      url: "https://tenkacloud.com/?lang=ja",
      runScripts: "outside-only",
    });
    const { window } = dom;
    Object.defineProperty(window, "fetch", {
      configurable: true,
      value: () => Promise.resolve({ ok: true, status: 200, json: () => Promise.resolve(config) }),
    });
    window.eval(read("landing/contact-form.js"));
    window.eval(read("landing/app.js"));
    // 設定取得は 2 段の then を挟むので、 マイクロタスクを流し切ってから触る。
    await new Promise((resolve) => setTimeout(resolve, 0));
    return window;
  }

  const control = (window: Window, key: string) =>
    window.document.querySelector(`[data-form-field="${key}"]`) as
      | HTMLInputElement
      | HTMLSelectElement
      | HTMLTextAreaElement;

  const banner = (window: Window) =>
    window.document.querySelector("[data-contact-form-status]") as HTMLElement;

  function fill(window: Window, key: string, value: string) {
    const el = control(window, key);
    el.value = value;
    el.dispatchEvent(new window.Event("input", { bubbles: true }));
    el.dispatchEvent(new window.Event("change", { bubbles: true }));
  }

  function submit(window: Window) {
    const form = window.document.querySelector("[data-contact-form]") as HTMLFormElement;
    form.dispatchEvent(new window.Event("submit", { bubbles: true, cancelable: true }));
  }

  it("should reveal the inline form only after the config validates", async () => {
    const window = await mount(CONFIG);
    const form = window.document.querySelector("[data-contact-form]") as HTMLFormElement;
    expect(form.hidden).toBe(false);
    expect(form.classList.contains("contact-form-ready")).toBe(true);
  });

  it("should keep the inline form hidden when the config cannot be loaded", async () => {
    const window = await mount({ formResponseUrl: "https://example.com/nope", fields: {} });
    const form = window.document.querySelector("[data-contact-form]") as HTMLFormElement;
    expect(form.hidden).toBe(true);
  });

  it("should mark every empty required field and move focus to the first one", async () => {
    const window = await mount(CONFIG);
    submit(window);

    expect(control(window, "name").getAttribute("aria-invalid")).toBe("true");
    expect(control(window, "organization").hasAttribute("aria-invalid")).toBe(false);
    expect(window.document.getElementById("contact-name-error")?.textContent).toBe(
      "必須項目を入力してください。",
    );
    expect(window.document.activeElement).toBe(control(window, "name"));
  });

  it("should reject a malformed email before the no-cors POST hides the failure", async () => {
    const window = await mount(CONFIG);
    fill(window, "email", "not-an-email");
    submit(window);

    expect(window.document.getElementById("contact-email-error")?.textContent).toBe(
      "メールアドレスの形式で入力してください。",
    );
  });

  it("should retract the summary message once every problem is corrected", async () => {
    const window = await mount(CONFIG);
    submit(window);
    expect(banner(window).textContent).toBe(
      "入力に不備があります。 各項目の説明を確認してください。",
    );

    fill(window, "name", "富田");
    // まだ他の必須が空なので、 まとめ表示は残る。
    expect(banner(window).textContent).not.toBe("");

    fill(window, "email", "taro@example.com");
    fill(window, "topic", "その他");
    fill(window, "message", "相談したいことがあります。");
    expect(banner(window).textContent).toBe("");
  });

  it("should refuse to run when the synced config disagrees with the markup", async () => {
    // 同期側だけ必須が外れた設定。 実行時に気づけないと、 LP は必須のはずの欄を
    // 空のまま送り、 Google に弾かれた事実が no-cors で消える。
    const drifted = structuredClone(CONFIG) as typeof CONFIG;
    drifted.fields.name.required = false;
    const window = await mount(drifted);
    const form = window.document.querySelector("[data-contact-form]") as HTMLFormElement;
    expect(form.hidden).toBe(true);
  });

  it("should refuse to run when a choice value drifts from the synced config", async () => {
    const drifted = structuredClone(CONFIG) as typeof CONFIG;
    drifted.fields.topic.choices = ["まったく別の選択肢"];
    const window = await mount(drifted);
    const form = window.document.querySelector("[data-contact-form]") as HTMLFormElement;
    expect(form.hidden).toBe(true);
  });
});
