import { fireEvent, render, screen } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { EventDetail } from "../api/events-client";
import type { AppConfig } from "../config";
import { I18nProvider } from "../i18n";
import { EventReportPage } from "./EventReport";

// useEventDetail が呼ぶ getEvent (= ApiClient.get) を mock。 AuthProvider 不要に倒すため
// useApiClient 自体をモジュールごと差し替える。
const mockGet = vi.fn();
vi.mock("../api/client", () => {
  const fakeClient = {
    get: (path: string) => mockGet(path),
    post: vi.fn(),
    patch: vi.fn(),
    del: vi.fn(),
    delJson: vi.fn(),
  };
  return {
    useApiClient: () => fakeClient,
    ApiError: class ApiError extends Error {},
  };
});

function makeDetail(overrides: Partial<EventDetail> = {}): EventDetail {
  return {
    eventId: "01HXEVENT0000000000000ABCD",
    name: "Spring Cloud Cup 2026",
    status: "ENDED",
    teamCount: 2,
    problemCount: 1,
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-21T00:00:00Z",
    expiresAt: 0,
    startsAt: "2026-05-21T09:00:00Z",
    endsAt: "2026-05-21T12:00:00Z",
    teams: [
      { teamId: "team-A", internalSlug: "alpha", displayName: "Team Alpha" },
      { teamId: "team-B", internalSlug: "bravo", displayName: "Team Bravo" },
    ],
    problems: [{ problemId: "battle/redis-spike", defaultRegion: "ap-northeast-1" }],
    deploymentsByProblem: {
      "battle/redis-spike": [
        { jobId: "j1", teamId: "team-A", status: "COMPLETE" },
        { jobId: "j2", teamId: "team-B", status: "FAILED" },
      ],
    },
    scoreEventsByTeam: [
      {
        teamId: "team-A",
        teamName: "Team Alpha",
        events: [
          {
            jobId: "j1",
            problemId: "battle/redis-spike",
            source: "flag",
            points: 100,
            result: "ok",
            occurredAt: "2026-05-21T10:30:00Z",
          },
        ],
      },
      {
        teamId: "team-B",
        teamName: "Team Bravo",
        events: [
          {
            jobId: "j2",
            problemId: "battle/redis-spike",
            source: "flag-wrong",
            points: -10,
            result: "wrong",
            occurredAt: "2026-05-21T10:35:00Z",
          },
        ],
      },
    ],
    ...overrides,
  };
}

const CONFIG: AppConfig = {
  cognitoDomain: "test.auth.example.com",
  cognitoClientId: "client",
  redirectUri: "http://localhost/callback",
  scope: "openid",
  tenantId: "tenant-test",
  tenantName: "ACME Cloud Academy",
  apiBaseUrl: "https://api.example.com",
};

function renderPage(detail: EventDetail) {
  mockGet.mockResolvedValue(detail);
  return render(
    <I18nProvider>
      <MemoryRouter initialEntries={[`/events/${detail.eventId}/report`]}>
        <Routes>
          <Route path="/events/:eventId/report" element={<EventReportPage config={CONFIG} />} />
          <Route path="/events/:eventId" element={<div>Event detail page</div>} />
        </Routes>
      </MemoryRouter>
    </I18nProvider>,
  );
}

afterEach(() => {
  mockGet.mockReset();
});

describe("EventReportPage", () => {
  it("should render all 6 sections with the loaded event data", async () => {
    renderPage(makeDetail());

    // Header (title + event name)
    expect(await screen.findByText("Spring Cloud Cup 2026")).toBeInTheDocument();
    expect(screen.getByText(/Event ID/i)).toBeInTheDocument();
    // Summary stats
    expect(screen.getByText(/Total deployments|総 deploy 件数/)).toBeInTheDocument();
    // Scoreboard
    expect(screen.getByText(/Final scoreboard|最終順位/)).toBeInTheDocument();
    expect(screen.getByText("Team Alpha")).toBeInTheDocument();
    // Per-problem breakdown
    expect(screen.getByText(/Per-problem breakdown|問題別ブレークダウン/)).toBeInTheDocument();
    // problem id appears in breakdown + disruption sections
    expect(screen.getAllByText("battle/redis-spike").length).toBeGreaterThanOrEqual(1);
    // Disruption section (has a flag-wrong)
    expect(screen.getByText(/Disruption|Disruption \/ Red Team/)).toBeInTheDocument();
    // Footer
    expect(screen.getByText(/Generated by TenkaCloud/)).toBeInTheDocument();
  });

  it("should hide the disruption section when there are no negative-point events", async () => {
    const detail = makeDetail({
      scoreEventsByTeam: [
        {
          teamId: "team-A",
          teamName: "Team Alpha",
          events: [
            {
              jobId: "j1",
              problemId: "battle/redis-spike",
              source: "flag",
              points: 100,
              result: "ok",
              occurredAt: "2026-05-21T10:30:00Z",
            },
          ],
        },
      ],
    });
    renderPage(detail);
    await screen.findByText("Spring Cloud Cup 2026");
    expect(screen.queryByText(/Red Team/)).not.toBeInTheDocument();
  });

  it("should let the operator edit the cover note and persist it across re-render", async () => {
    const { rerender } = renderPage(makeDetail());
    await screen.findByText("Spring Cloud Cup 2026");
    const textarea = screen.getByLabelText(/Cover note|cover note/i) as HTMLTextAreaElement;
    fireEvent.change(textarea, { target: { value: "Custom intro for ACME" } });
    expect(screen.getByTestId("event-report-cover-note")).toHaveTextContent(
      "Custom intro for ACME",
    );
    // Re-render the same tree → state still preserved (= same component instance).
    rerender(
      <I18nProvider>
        <MemoryRouter initialEntries={["/events/01HXEVENT0000000000000ABCD/report"]}>
          <Routes>
            <Route path="/events/:eventId/report" element={<EventReportPage config={CONFIG} />} />
          </Routes>
        </MemoryRouter>
      </I18nProvider>,
    );
    expect(screen.getByTestId("event-report-cover-note")).toHaveTextContent(
      "Custom intro for ACME",
    );
  });

  it("should inject the print stylesheet into document head while mounted", async () => {
    const { unmount } = renderPage(makeDetail());
    await screen.findByText("Spring Cloud Cup 2026");
    const style = document.getElementById("tenkacloud-event-report-print-style");
    expect(style).not.toBeNull();
    expect(style?.textContent).toContain("@media print");
    unmount();
    expect(document.getElementById("tenkacloud-event-report-print-style")).toBeNull();
  });

  it("should expose a download HTML button and trigger a Blob download on click (#1317)", async () => {
    renderPage(makeDetail());
    await screen.findByText("Spring Cloud Cup 2026");

    // jsdom が URL.createObjectURL を持たないので spy で代用。 click を確認できれば
    // blob path に乗っていることを検証できる。
    const createSpy = vi.fn().mockReturnValue("blob:test-html");
    const revokeSpy = vi.fn();
    Object.defineProperty(URL, "createObjectURL", { value: createSpy, configurable: true });
    Object.defineProperty(URL, "revokeObjectURL", { value: revokeSpy, configurable: true });

    const button = screen.getByTestId("event-report-download-html") as HTMLButtonElement;
    expect(button).toBeInTheDocument();
    expect(button.textContent).toMatch(/HTML/);

    fireEvent.click(button);
    expect(createSpy).toHaveBeenCalledTimes(1);
    const blobArg = createSpy.mock.calls[0]?.[0] as Blob;
    expect(blobArg).toBeInstanceOf(Blob);
    expect(blobArg.type).toContain("text/html");
  });

  it("should expose a download Markdown button and trigger a Blob download on click (#1317)", async () => {
    renderPage(makeDetail());
    await screen.findByText("Spring Cloud Cup 2026");

    const createSpy = vi.fn().mockReturnValue("blob:test-md");
    const revokeSpy = vi.fn();
    Object.defineProperty(URL, "createObjectURL", { value: createSpy, configurable: true });
    Object.defineProperty(URL, "revokeObjectURL", { value: revokeSpy, configurable: true });

    const button = screen.getByTestId("event-report-download-md") as HTMLButtonElement;
    expect(button).toBeInTheDocument();
    expect(button.textContent).toMatch(/Markdown/);

    fireEvent.click(button);
    expect(createSpy).toHaveBeenCalledTimes(1);
    const blobArg = createSpy.mock.calls[0]?.[0] as Blob;
    expect(blobArg).toBeInstanceOf(Blob);
    expect(blobArg.type).toContain("text/markdown");
  });

  it("should wrap the printable content in the .event-report-page container (#1317 whitelist anchor)", async () => {
    renderPage(makeDetail());
    await screen.findByText("Spring Cloud Cup 2026");
    const root = document.querySelector(".event-report-page");
    expect(root).not.toBeNull();
    // 本文の core text が root の子孫に居ること
    expect(root?.textContent ?? "").toContain("Spring Cloud Cup 2026");
  });
});
